### ISSUE TITLE
Integration tests - fix intermittent failure: Unexpected method call Logging.close()

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1541]
```
Tests in error: 
  ITLoggingTest.testListSinksAsync » Logging io.grpc.StatusRuntimeException: INT...

Exception in thread "Thread-0" java.lang.AssertionError: 
  Unexpected method call Logging.close():
    Logging.write([LogEntry{logName=null, resource=null, timestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}): expected: 1, actual: 1
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
	at com.sun.proxy.$Proxy11.close(Unknown Source)
	at com.google.cloud.logging.LoggingHandler.close(LoggingHandler.java:375)
	at java.util.logging.LogManager.resetLogger(LogManager.java:1346)
	at java.util.logging.LogManager.reset(LogManager.java:1332)
	at java.util.logging.LogManager$Cleaner.run(LogManager.java:239)
```

https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/jobs/191392244
https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/jobs/191530116

**Comment by gregw** [comment]
Note that I have fixed (or at least avoided) this issue in PR  https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1535  by implemented close to be a noop that avoids calling the mock close.

**Comment by garrettjonesgoogle** [comment]
Closing out issue now.
