### ISSUE TITLE
URLFetchServiceStreamHandler$Connection cannot be cast to HttpsURLConnection

### ISSUE THREAD

**Issue by grembek** [GoogleCloudPlatform/google-cloud-java#1614]
Hi,

I am using the [Zendesk java client ](https://github.com/cloudbees/zendesk-java-client) on my Google Cloud App Engine and I have a runtime issue that prevents me from using the SDK. I am using the SDK from a servlet, what might I be doing wrong and would it work if I would use the SDK NOT from the servlet?

Thanks

```
Uncaught exception from servlet java.lang.ClassCastException: com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:184)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:147)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:118)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:506)
	at org.zendesk.client.v2.Zendesk.submit(Zendesk.java:1751)
	at org.zendesk.client.v2.Zendesk.access$1300(Zendesk.java:90)
```

**Comment by garrettjonesgoogle** [comment]
This doesn't appear to have anything to do with `google-cloud-java`. Maybe check this page for more info:

https://cloud.google.com/appengine/docs/java/issue-requests?csw=1#Using_HttpURLConnection

If you have no control over Zendesk code, maybe you might want to file an issue against Zendesk.

Closing this issue.
