### ISSUE TITLE
TRANSLATE: Using 0.10.0-alpha from the docs causes java.lang.ClassNotFoundException: com.google.cloud.ServiceDefaults

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-java#1780]
I think this probably happens if you just follow the getting started but my occurrence happened in:
https://github.com/patflynn/kplay/tree/broken-translate-api

You'll need to run cd into the spring-boot-simple directory and run mvn spring-boot:run
and then hit localhost:8080/visit

(that endpoints uses datastore so you'll need some creds in your environment)

0.9.4-alpha works fine.

```

java.lang.ClassNotFoundException: com.google.cloud.ServiceDefaults
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_91]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at hello.DemoController.visit(DemoController.java:36) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

```

**Comment by garrettjonesgoogle** [comment]
You are using version `0.9.3-beta` of google-cloud-datastore, so it is likely that version `0.9.3-beta` of google-cloud-core is being used, which doesn't have `ServiceDefaults`. You always need to keep the google-cloud-* packages at the same version.

**Comment by patflynn** [comment]
Aha I did not realize this.  Do we document it somewhere?  It should probably be a big warning on each individual libraries getting started.

So does that mean that every release entails a release of all the libraries in this repo with a common version?

**Comment by garrettjonesgoogle** [comment]
We don't have it documented anywhere yet. It's worth adding I think.

Yes, the release process will release all libraries with a common version, even the libraries that haven't changed themselves (since often there will be dependencies that changed).

**Comment by patflynn** [comment]
how are you guys going to GA subsets of these libraries if they all share
the same version?

**Comment by garrettjonesgoogle** [comment]
We'll have a slightly more complicated situation when we go GA - the GA clients will be at one version (1.x), and the alpha/beta clients will be at another version (0.x). They will still all move forward in lockstep, though.

**Comment by patflynn** [comment]
How do the users of the APIs know which versions go with which?

I'm having an issue now where I assumed that I would just extract the common version to a property in my pom but 0.10.0-beta from the datastore instructions doesn't resolve to a translate version, and 0.9.4-alpha in the translate API instructions don't resolve to a datastore version.

**Comment by patflynn** [comment]
@ludoch 
@rdayal

**Comment by garrettjonesgoogle** [comment]
I would suggest just tracking a couple versions like we do in the core google-cloud-java pom.xml:

```
    <alpha.version>0.10.1-alpha-SNAPSHOT</core.version>
    <beta.version>0.10.1-beta-SNAPSHOT</beta.version>
```

later, add a GA version:

```
    <ga.version>1.0.1-SNAPSHOT</core.version>
```

As for which versions go with which, we'll have the latest coordinating alpha/beta/ga versions in the main README.md.

**Comment by garrettjonesgoogle** [comment]
I don't think there is a good way to document this in a way that people will actually read (besides the 1% of people who read reference docs straight through for fun). I'm going to resolve this because there isn't a problem in the scenario where users specify the right versions together.

**Comment by patflynn** [comment]
What about using a BOM? 

http://howtodoinjava.com/maven/maven-bom-bill-of-materials-dependency/

**Comment by garrettjonesgoogle** [comment]
We are using dependency management already in our poms, but that doesn't help people depending on the wrong versions of our stuff in their own poms.

**Comment by patflynn** [comment]
but can't we just always tell the user to import our BOM as the first step to importing our libraries?

**Comment by patflynn** [comment]
@saturnism do you have an opinion on this?

**Comment by garrettjonesgoogle** [comment]
Marking issue as open since there is an ongoing conversation

**Comment by saturnism** [comment]
the dependency management stuff currently is used for our own library builds. when a user wants to use our library, they do need to specify a version...

*unless* that we make our pom.xml easily importable (having dep management was the first step). Users can import a specific version of our pom, and in the individual dependencies, they just need to specify groupId and artifactId.

This is commonly used for Spring application.  E.g., they have a release train that contains all the individual component releases. For a release train, they have an importable pom (BOM). All I need is to import the BOM, and I can be sure that I'm using library versions that they tested with.

**Comment by saturnism** [comment]
Here is an example for Spring Cloud dependencies: http://projects.spring.io/spring-cloud/

**Comment by patflynn** [comment]
@garrettjonesgoogle any thoughts on this?  Are we likely to see a BOM published in Q3?  This could be our answer to the diamond dep problem.

**Comment by garrettjonesgoogle** [comment]
It would only solve misuse of this library, it wouldn't solve diamond dependency conflicts with other libraries we don't control. 

I'd like to see more evidence of the priority/impact before committing to working on it.

**Comment by patflynn** [comment]
I wouldn't think that diamond dependency conflicts for libraries we don't
control is solvable.

**Comment by garrettjonesgoogle** [comment]
There is the "area in between" - solving diamond dependency conflicts among Google's open source libraries, which are technically ones that the team of google-cloud-java doesn't own, but which can be influenced. That is the one worth putting effort into I think.

**Comment by garrettjonesgoogle** [comment]
Closing out this issue - filed a new issue to introduce a BOM: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2307
