### ISSUE TITLE
DEADLINE_EXCEEDED, google-cloud-monitoring

### ISSUE THREAD

**Issue by jonathanbl** [GoogleCloudPlatform/google-cloud-java#1836]
This is similar to #1430 

OS version: OS X 10.10.5 (14F27), Kernel Version: Darwin 14.5.0

I am having the same issue with _google-cloud-monitoring:0.9.4-alpha_ and _netty-all:4.1.3.Final_. Every time I execute my Java process (see code attached), I end up with the following exception. 
Let me know if you need me to provide more details. 

com.google.api.gax.grpc.ApiException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at com.google.api.gax.grpc.ExceptionTransformingCallable$ExceptionTransformingFuture.onFailure(ExceptionTransformingCallable.java:107)
	at com.google.api.gax.grpc.ListenableFutureDelegate$1.onFailure(ListenableFutureDelegate.java:52)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:466)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.grpc.Status.asRuntimeException(Status.java:545)
	... 13 more

[java-monitoring.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/883365/java-monitoring.txt)

**Comment by garrettjonesgoogle** [comment]
Could you set your logging level to FINE to see if you see logs that say `Unable to load the library: netty-tcnative-linux-x86_64`?

**Comment by jonathanbl** [comment]
What would be the best way to change the log level?

**Comment by garrettjonesgoogle** [comment]
Make the following call in `main` before your code executes:

```
Logger.getLogger("").setLevel(Level.FINE);
```

Also, use a logging.properties file with these settings:

```
.level = FINE

handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = FINE
```

**Comment by jonathanbl** [comment]
Here's the full output when I run with FINE level 

[gcloud-monitoring.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/885938/gcloud-monitoring.txt)

**Comment by garrettjonesgoogle** [comment]
Could you try with the latest version of google-cloud-monitoring? We have upgraded to a more recent grpc + tcnative that 1) throws an up-front error when tcnative loading fails, and 2) reduces the number of cases where there are tcnative conflicts.

**Comment by garrettjonesgoogle** [comment]
No response from issue filer, so I'm closing this out. We are currently tracking issues with making calls in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2266 - please follow along there if you are still having problems.
