### ISSUE TITLE
Unknown error getting image annotations

### ISSUE THREAD

**Issue by vikceo** [GoogleCloudPlatform/google-cloud-java#1860]
Input is:https://res.cloudinary.com/viksphotography/image/upload/v1491023435/emt2sgakliae5gap9xks.jpg
[WARNING] /echo
java.io.IOException: Unknown error getting image annotations
	at photography.viks.ig.DetectLabels.labelImage(DetectLabels.java:161)
	at com.example.endpoints.EchoServlet.doPost(EchoServlet.java:63)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
plz advise

**Comment by danielcompton** [comment]
There isn't enough information here to help you, and it looks likely that this is a usage issue. StackOverflow is probably a better avenue to resolve this?

**Comment by vikceo** [comment]
nah it's a bug with api. the sample code and valid image simply fails. other images works fine with same code.

**Comment by shinfan** [comment]
@swcloud Can you take a look at this issue? It looks like an issue on the API.

**Comment by swcloud** [comment]
@vikceo That's because for that image no label was detected. The user code probably failed to handle that case.

**Comment by garrettjonesgoogle** [comment]
@vikceo are you able to show what your code looks like that calls the vision API?

**Comment by garrettjonesgoogle** [comment]
No response, so I'm going to close this out. Feel free to re-open if you're able to provide more information.
