### ISSUE TITLE
Getting No Method Error com.google.protobuf.AbstractMessage.newBuilderForType while calling datastore in java

### ISSUE THREAD

**Issue by Saurabh111191** [GoogleCloudPlatform/google-cloud-java#1891]
```
Err: 
WARN  [2017-04-10 18:30:55,863] [ ] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED **org.eclipse.jetty.server.Server@2ad2b274: java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessage.newBuilderForType(Lcom/google/protobuf/AbstractMessage$BuilderParent;)Lcom/google/protobuf/Message$Builder;
! java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessage.newBuilderForType(Lcom/google/protobuf/AbstractMessage**$BuilderParent;)Lcom/google/protobuf/Message$Builder;
! at com.google.protobuf.SingleFieldBuilderV3.getBuilder(SingleFieldBuilderV3.java:142)
! at com.google.protobuf.RepeatedFieldBuilderV3.addBuilder(RepeatedFieldBuilderV3.java:413)
! at com.google.datastore.v1.Query$Builder.addKindBuilder(Query.java:1713)
! at com.google.cloud.datastore.StructuredQuery.toPb(StructuredQuery.java:1110)
! at com.google.cloud.datastore.StructuredQuery.populatePb(StructuredQuery.java:1089)
! at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:72)
! at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:57)
! at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:82)
! at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:73)
! at com.nis.userService.core.managed.DeltaContactConsumer.start(DeltaContactConsumer.java:44)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
! at org.eclipse.jetty.server.Server.start(Server.java:342)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
! at org.eclipse.jetty.server.Server.doStart(Server.java:290)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
! at io.dropwizard.cli.Cli.run(Cli.java:70)
! at io.dropwizard.Application.run(Application.java:72)
```

Sample Code that I am running:
      
```
Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
            EntityQuery.Builder queryBuilder = Query.newEntityQueryBuilder().setKind("Device")
                    .setLimit(10);
        while (true) {
            if (pageCursor != null) {
                queryBuilder.setStartCursor(pageCursor);
            }
            QueryResults<Entity> tasks = datastore.run(queryBuilder.build());
            while (tasks.hasNext()) {
                Entity task = tasks.next();
                userLocations.add(new UserLocation(task));
            }
            Cursor nextPageCursor = tasks.getCursorAfter();
            pageCursor = nextPageCursor;
            if (nextPageCursor == null) {
                break;
            }
        }
  
```

**Comment by garrettjonesgoogle** [comment]
@Saurabh111191 can I get your dependency tree? In particular, I'd like to know what protobuf-related packages you are pulling in.

**Comment by garrettjonesgoogle** [comment]
No response, so I'm going to close out this issue. Feel free to re-open if you have more details to provide.
