### ISSUE TITLE
null pointer on startup

### ISSUE THREAD

**Issue by jehrlich** [GoogleCloudPlatform/google-cloud-java#1965]
Following instructions in the README, I added 
`libraryDependencies += "com.google.cloud" % "google-cloud-storage" % "0.13.0-beta"` to my build.sbt. This causes a null pointer exception on startup:

> --- (Running the application, auto-reloading is enabled) ---

java.lang.NullPointerException
	at io.netty.channel.group.DefaultChannelGroup.add(DefaultChannelGroup.java:146)
	at play.core.server.NettyServer.bind(NettyServer.scala:140)
	at play.core.server.NettyServer.play$core$server$NettyServer$$bindChannel(NettyServer.scala:224)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:216)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:216)
	at scala.Option.map(Option.scala:146)
	at play.core.server.NettyServer.<init>(NettyServer.scala:216)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:235)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:64)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:54)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:playRun) java.lang.reflect.InvocationTargetException
[error] Total time: 8 s, completed Apr 21, 2017 5:44:08 PM

Process finished with exit code 1

This is using IntelliJ with Scala plugin and Play Framework. Removing the dependency eliminates the nullpointer. Interestingly adding 

   ` "com.seancheatham" %% "storage-google-cloud" % "0.1.3",//https://index.scala-lang.org/seancheatham/scala-storage-wrappers`

to build.sbt works just fine. This is a thin wrapper listing google-cloud-storage as a dependency, so an adequate work-around for my purposes. To be explicit with the two lines in my build file as below everything works. 
```
  "com.seancheatham" %% "storage-google-cloud" % "0.1.3",
  //"com.google.cloud" % "google-cloud-storage" % "0.13.0-beta",
```
If I comment the first and uncomment the second, I get a null pointer on startup.

**Comment by jehrlich** [comment]
This link https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-storage#google-cloud-java-client-for-storage recommends a newer SDK: 

> If you are using SBT, add this to your dependencies
> libraryDependencies += "com.google.cloud" % "google-cloud-storage" % "1.0.0-rc2"
> 

I had to clean my compiler cache, but after doing that, 1.0.0-rc2 compiles, at least. README needs updating!

**Comment by shinfan** [comment]
Closing this issue since the the new README now recommends 1.0.1.
