### ISSUE TITLE
PubSub Subscriber startAsync nosuchmethoderror

### ISSUE THREAD

**Issue by autodidacticon** [GoogleCloudPlatform/google-cloud-java#2056]
I have a subscriber defined as follows:
```
  //nested class for access to 'store' methods
  class PubSubMessageReceiver extends MessageReceiver {
    override def receiveMessage(message: PubsubMessage, consumer: AckReplyConsumer): Unit = {
     // .. business logic
      //acknowledge message
      consumer.ack()
    }
  }

val subscriber = Subscriber.defaultBuilder(subscriptionName, new PubSubMessageReceiver).build()
```

However when calling `subscriber.startAsync` I receive the following error:

```
java.lang.NoSuchMethodError: com.google.api.core.AbstractApiService$InnerService.startAsync()Lcom/google/common/util/concurrent/Service;
	at com.google.api.core.AbstractApiService.startAsync(AbstractApiService.java:121)
	at com.google.cloud.pubsub.spi.v1.Subscriber.startAsync(Subscriber.java:218)
```

**Comment by autodidacticon** [comment]
The
