### ISSUE TITLE
[NIO] Inconsistent failure messages

### ISSUE THREAD

**Issue by Horneth** [GoogleCloudPlatform/google-cloud-java#2090]
Different operations have inconsistent error messages such that for example trying to read from a non existing object, or trying to get its size do not return the same path format.

Opening a readChannel on a non existing object yields

```
java.nio.file.NoSuchFileException: gs://nonexistingbucket/path/doesnt/exist
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.fetchSize(CloudStorageReadChannel.java:196)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.<init>(CloudStorageReadChannel.java:72)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.create(CloudStorageReadChannel.java:62)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newReadChannel(CloudStorageFileSystemProvider.java:268)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:229)
```

And trying to get attributes on the same non existing object yields

```
java.nio.file.NoSuchFileException: nonexistingbucket/path/doesnt/exist
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.readAttributes(CloudStorageFileSystemProvider.java:575)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
	at java.nio.file.Files.walk(Files.java:3574)
```

**Comment by vam-google** [comment]
@Horneth please check https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2096

**Comment by vam-google** [comment]
Please check https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2330 (a duplicate PR, since travis cannot build the original PR).

**Comment by vam-google** [comment]
Merged.
