### ISSUE TITLE
APIs requires auth dependencies to work correctly

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2192]
Using only `com.google.cloud:google-cloud-errorreporting:0.20-alpha` :
```
java.lang.NoClassDefFoundError: com/google/auth/ServiceAccountSigner
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:549)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:475)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:54)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:125)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
	at com.google.api.gax.grpc.ChannelAndExecutor.create(ChannelAndExecutor.java:65)
	at com.google.api.gax.grpc.ClientSettings.getChannelAndExecutor(ClientSettings.java:91)
	at com.google.cloud.errorreporting.v1beta1.ReportErrorsServiceClient.<init>(ReportErrorsServiceClient.java:122)
```

Current workaround is to include : 
```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.auth</groupId>
        <artifactId>google-auth-library-credentials</artifactId>
        <version>0.6.1</version>
      </dependency>
      <dependency>
        <groupId>com.google.auth</groupId>
        <artifactId>google-auth-library-oauth2-http</artifactId>
        <version>0.6.1</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by shinfan** [comment]
@jabubake Is this a documentation issue or something needs to be changed in the pom?

**Comment by shinfan** [comment]
This sounds like a severe issue I will mark this as P1

**Comment by jabubake** [comment]
in the pom.

**Comment by jabubake** [comment]
Same is true for google-cloud-language as well.

**Comment by jabubake** [comment]
FYI, @gguuss @lesv

**Comment by jabubake** [comment]
@garrettjonesgoogle FYI

**Comment by gguuss** [comment]
I went ahead and [put together a PR](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/732) to include the auth dependency.

**Comment by gguuss** [comment]
Once this issue resolves, we'll need to update the language sample's POM.

**Comment by jabubake** [comment]
@neozwu  : DLP API as well.

**Comment by garrettjonesgoogle** [comment]
I believe the root cause is that Maven is making a bad, bad choice when resolving this dependency. If maven used the latest version in the tree (which Gradle does), we would not be seeing this issue; we do indeed have the latest version in the dependency tree.

**Comment by lesv** [comment]
`mvn dependency:tree -Dverbose`
https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html

It sounds like something is listed twice and picking the wrong one.

**Comment by garrettjonesgoogle** [comment]
Potentially we could subvert Maven's dependency choice by putting the google-auth-library-java dependency in google-cloud-core-grpc. We would have to experiment and see if that fixes the problem.

**Comment by neozwu** [comment]
I'm working on migrating from maven to gradle. This would be something the migration should take care of.

**Comment by garrettjonesgoogle** [comment]
Consumers of google-cloud-java using Maven will likely still hit this issue even if we are using Gradle.

**Comment by jabubake** [comment]
@neozwu : +1 to what @garrettjonesgoogle just said.
