### ISSUE TITLE
Gcloud PubSub Java implementation - java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by michaelthecsguy** [GoogleCloudPlatform/google-cloud-java#2237]
I use the sample snippet from GCloud documentation to receive msg as a subscriber. My pubsub gcloud jar version is 0.19.0-alpha

The problem is that I can receive the msgConent with attribute map but I keep having this exception:

`2017-07-12 16:52:25,219 [grpc-default-worker-ELG-1-16] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by io.grpc.netty.NettyClientHandler$3.operationComplete() java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@fbf4a6d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@25cbe860[Terminated, pool size = 35, active threads = 0, queued tasks = 0, completed tasks = 2403] at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:110) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.onReady(ClientCallImpl.java:573) at io.grpc.internal.DelayedStream$DelayedStreamListener.onReady(DelayedStream.java:398) at io.grpc.internal.AbstractStream2$TransportState.notifyIfReady(AbstractStream2.java:305) at io.grpc.internal.AbstractStream2$TransportState.onStreamAllocated(AbstractStream2.java:248) at io.grpc.netty.NettyClientStream$TransportState.setHttp2Stream(NettyClientStream.java:227) at io.grpc.netty.NettyClientHandler$3.operationComplete(NettyClientHandler.java:429) at io.grpc.netty.NettyClientHandler$3.operationComplete(NettyClientHandler.java:417) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)`

After that, the program shuts and stop listening to msg. How to resolve this interruption and I even get rid of finally clause that has subscriber.stopAsync()

**Comment by michaelthecsguy** [comment]
found the issue... the runtime has to keep running otherwise, it is forcing to stop Async.
