### ISSUE TITLE
Copying large object to a different bucket always times out

### ISSUE THREAD

**Issue by Safyia** [GoogleCloudPlatform/google-cloud-java#2243]
I am trying to copy a 2GB blob from one bucket to another, using the `copyTo` method of the blob. This always fails with the following exception:
```
Exception in thread "main" com.google.cloud.storage.StorageException: Read timed out
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.rewrite(HttpStorageRpc.java:661)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.openRewrite(HttpStorageRpc.java:621)
	at com.google.cloud.storage.StorageImpl$15.call(StorageImpl.java:433)
	at com.google.cloud.storage.StorageImpl$15.call(StorageImpl.java:430)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
	at com.google.cloud.storage.StorageImpl.copy(StorageImpl.java:430)
	at com.google.cloud.storage.Blob.copyTo(Blob.java:493)
	at com.google.cloud.storage.Blob.copyTo(Blob.java:546)
```
Copying within the same bucket works as expected.  I am using the `0.20.1-alpha` version of the google cloud library.

**Comment by vam-google** [comment]
It seem like the request times out because the blob is big and it takes a lot of time to transfer it. I believe copying within the same bucket consumes less resources, is faster on the backend an that is why the request does not timeout.

Please try to increase timeout limit (20000 milliseconds is the default one) and execute the operation again. The [RemoteStorageHelper](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java#L129) is a good example of how it can be done:

```java
HttpTransportOptions transportOptions = StorageOptions.getDefaultHttpTransportOptions();
transportOptions = transportOptions.toBuilder().setConnectTimeout(60000).setReadTimeout(60000)
    .build();
StorageOptions storageOptions = StorageOptions.newBuilder()
    .setRetrySettings(retrySettings())
    .setTransportOptions(transportOptions)
    .build();
Storage storage = storageOptions.getService();
```
@Safyia, please let us know if it fixes your issue.

**Comment by vam-google** [comment]
Closing as there was no response for 3 days. Hopefully increasing the timeout helps. If no, please feel free to reopen the issue.

**Comment by daudn** [comment]
Im getting this same issue. I am using Nextflow which utilises `gsutil` to upload files to buckets in GCP. Is there any way around this? I have noticed this happens when I try to upload multiple LARGE files. 

Each file(s) approx 300MB, and about 100 of those. 

When I try to upload 50, it works like a charm. But has broken on 100 files 3 times now. I am running a hybrid workflow (that relies on uploading data to GCP buckets) - Is there any way around this or can I only run one workflow at a time?
