### ISSUE TITLE
How can I set bigquery streaming insert timeout?

### ISSUE THREAD

**Issue by gyamxxx** [GoogleCloudPlatform/google-cloud-java#2297]
I caused Error.
How can I set timeout (read timeout?)?
```
com.google.cloud.bigquery.BigQueryException: Read timed out
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:86)
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:283)
        at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:443)
        at jp.co.xxx.BigQuerySender.insertStreamingData(BigQuerySender.java:68)
        at jp.co.xxx.BigQuerySender.insert(BigQuerySender.java:60)
        at jp.co.xxx.GcpSender.run(GcpSender.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:281)

```

**Comment by vam-google** [comment]
The `HttpTransportOptions` class allows to set read and connect timeouts. Please check [RemoteBigQueryHelper](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelper.java#L117) code of an example how it can be done:

```java
HttpTransportOptions transportOptions = BigQueryOptions.getDefaultHttpTransportOptions();
transportOptions = transportOptions.toBuilder().setConnectTimeout(60000).setReadTimeout(60000)
    .build();
BigQueryOptions bigqueryOptions = BigQueryOptions.newBuilder()
    .setRetrySettings(retrySettings())
    .setTransportOptions(transportOptions)
    .build();

BigQuery bigquery = bigqueryOptions.getService();
//bigquery.insertAll()
```

Please let us know if it resolves your issue.

**Comment by gyamxxx** [comment]
@vam-google 
Thanks you very much !
It fixed the exception, but new exception was happened like this...
```
  j.c.c.BigQuerySender Remote host closed connection during handshake
com.google.cloud.bigquery.BigQueryException: Remote host closed connection during handshake
    at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:86)
    at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:283)
    at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:443)
    at jp.co.xxx.BigQuerySender.insertStreamingData(BigQuerySender.java:71)
    at jp.co.xxx.BigQuerySender.insert(BigQuerySender.java:63)
    at jp.co.xxx.GcpSender.run(GcpSender.java:67)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
    at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:281)
    ... 11 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.InputRecord.read(InputRecord.java:505)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    ... 25 common frames omitted
```
My code is:
```
        BigQueryOptions.Builder builder =  BigQueryOptions.newBuilder()
                .setProjectId(PROJECT_ID);

        HttpTransportFactory httpTransportFactory = new ProductionHttpTransportFactory();
        TransportOptions transportOptions = HttpTransportOptions.newBuilder()
                .setHttpTransportFactory(httpTransportFactory)
                .setReadTimeout(0)
                .build();
        builder.setCredentials(ServiceAccountCredentials.fromStream(Files.newInputStream(path), httpTransportFactory)).setTransportOptions(transportOptions);
        BigQuery bigquery = builder.build().getService();
```

**Comment by vam-google** [comment]
This must be authentication related issue now. Are you sure that you are using a valid json service account key? Which `httpTransportFactory` are you using in this example (`ProductionHttpTransportFactory` looks like an external class)? Please check [Authentication](https://github.com/GoogleCloudPlatform/google-cloud-java#authentication) section and try other ways of authentication. If other ways work, then most probably something is wrong with either your key or transport factory.

**Comment by gyamxxx** [comment]
oops, ```ProductionHttpTransportFactory ``` is:
```
public final class ProductionHttpTransportFactory implements HttpTransportFactory {
    private static final Logger logger = LoggerFactory.getLogger(ProductionHttpTransportFactory.class);
    private static HttpTransport HTTP_TRANSPORT;

    static {
        try {
            HTTP_TRANSPORT = newProxyTransport();
        } catch (GeneralSecurityException | IOException e) {
            logger.error(e.getMessage(), e);
        }
    }

    private static HttpTransport newProxyTransport() throws GeneralSecurityException, IOException {
        return new NetHttpTransport.Builder()
                .trustCertificates(GoogleUtils.getCertificateTrustStore())
                .setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(PROXY_SERVER, PROXY_PORT)))
                .build();
    }

    @Override
    public HttpTransport create() {
        return HTTP_TRANSPORT;
    }
}
```

**Comment by vam-google** [comment]
You are using proxy in your configuration and I believe the exceptions you encounter are related to that. It is hard to tell more as there is too many unknown things: 

1) your lib versions,
2) the actual proxy you are using and its configuration (honestly, I'm not even sure that using proxies is supported)
3) the request you are trying to make
4) the https.protocols you are using
5) have you ensured validity and compatibility of the credentials (`Files.newInputStream(path)`), certificates and protocols you are using?

Also, is this authentication issue related to the original **timeout problem** you had?

**Comment by gyamxxx** [comment]
1. ```com.google.cloud:google-cloud-bigquery:0.21.1-beta```
 2. I can't confirm proxy setting, but I know this proxy is Apache HTTP server.
 3. streaming insert. It retry succeeded to send data when this error was occured.
 4. I don't know how to check https.protocols.
 5. I confirmed that service account json file(using for ```Files.newInputStream(path)```) of the GCP IAM page exists.

Timeout problem is resolved. May I open new issue?

**Comment by vam-google** [comment]
Yes, feel free to open a new issue (putting a ling to this one). Closing this issue as resolved. If you choose to open a new issue, please clarify if you always receive this SSL error, or only sometimes (i.e. is it sporadic or no). If it is sporadic, I suspect the actual proxy you are using may be the problem, not the bigquery service or the client libraries.
