### ISSUE TITLE
GAE Java8 Standard, BigQuery API throws "Invalid Project Id"

### ISSUE THREAD

**Issue by ifigotin** [GoogleCloudPlatform/google-cloud-java#2300]
Environment: App Engine Standard Java 8.
In pom.xml I have the following:
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud</artifactId>
  <version>0.21.0-alpha</version>
</dependency>
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-bigquery</artifactId>
  <version>0.21.1-beta</version>
</dependency>

My app has this example in a servlet:
    BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();
    String datasetId = "my_dataset_id";
    bigquery.create(DatasetInfo.newBuilder(datasetId).build());

When the servlet is called, I get the following exception:
com.google.cloud.bigquery.BigQueryException: Invalid project ID 'MyProjIDHere'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. IDs must start with a letter and may not end with a dash.
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:86)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:141)
	at com.google.cloud.bigquery.BigQueryImpl$1.call(BigQueryImpl.java:172)
	at com.google.cloud.bigquery.BigQueryImpl$1.call(BigQueryImpl.java:169)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:169)
	at com.google.test.HelloAppEngine.doGet(HelloAppEngine.java:56)

**Comment by ifigotin** [comment]
I also tried a Logging API example in my Java8 GAE Standard app:
    LoggingOptions options = LoggingOptions.getDefaultInstance();
    try(Logging logging = options.getService()) {
      MetricInfo metricInfo = MetricInfo.newBuilder("test-metric", "severity >= ERROR")
          .setDescription("Log entries with severity higher or equal to ERROR")
          .build();
      logging.create(metricInfo);
    }

The error is similar, so it may be related:
java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:240)
        at com.google.cloud.logging.LoggingOptions.<init>(LoggingOptions.java:102)
        at com.google.cloud.logging.LoggingOptions$Builder.build(LoggingOptions.java:96)
        at com.google.cloud.logging.LoggingOptions.getDefaultInstance(LoggingOptions.java:55)

**Comment by lesv** [comment]
@ifigotin Can you retest w/ 0.24.0-beta
??
