### ISSUE TITLE
java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.

### ISSUE THREAD

**Issue by NagarajP** [GoogleCloudPlatform/google-cloud-java#2310]
Hi,
 
I am trying to read the content of StackDriver Logging . It is standalone java program.

However getting the following exception:

java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:66)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:58)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:445)
	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:134)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:108)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:432)
	at com.mycompany.googlecomponents.example.App.<init>(App.java:33)
	at com.mycompany.googlecomponents.example.App.main(App.java:38)
Caused by: java.io.IOException: java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:140)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:64)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:174)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:151)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:139)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:109)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:470)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:338)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:305)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:125)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:110)
	at com.google.api.gax.grpc.GrpcTransportProvider.getTransport(GrpcTransportProvider.java:98)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:111)

java program:
=========

```
public class App {
	
	private final Logging logging = LoggingOptions.getDefaultInstance().getService();

	public static void main(String[] args) {
		String filter ="logName=projects/*************************_log";
		App obj =  new App();
		obj.listLogEntries(filter);
	}
	
	public Page<LogEntry> listLogEntries(String filter) {
	    Page<LogEntry> entries = logging.listLogEntries(EntryListOption.filter(filter));
	    for (LogEntry entry : entries.iterateAll()) {
	      System.out.println("entry:::"+entry.toString());
	    }
	    return entries;
	  }
}
```
snippet of pom.xml file 
-------------------------

```
**<properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
   </properties>
  
  <dependencies>
  	<dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-logging</artifactId>
      <version>1.3.1</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.5.Final</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>**
```

Any suggestion? Thanks.

**Comment by garrettjonesgoogle** [comment]
This is likely the same issue as https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2266 . I'm closing out the present issue; follow in #2266 .

**Comment by saturnism** [comment]
For those that landed on this issue from search, please see gRPC troubleshooting guide https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting
