### ISSUE TITLE
Spanner integration tests failing with internal error "Invalid query plan"

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2326]
See https://ci.appveyor.com/project/googlejavacloud/google-cloud-java-v0gf7/build/682#L5892

Two tests failed - `analyzePlan` and `analyzeProfile`. The trace for `analyzeProfile` is below.

```
Tests run: 50, Failures: 0, Errors: 2, Skipped: 2, Time elapsed: 10.794 sec <<< FAILURE! - in com.google.cloud.spanner.it.ITQueryTest
analyzeProfile(com.google.cloud.spanner.it.ITQueryTest)  Time elapsed: 0.047 sec  <<< ERROR!
com.google.cloud.spanner.SpannerException: INTERNAL: Invalid query plan.
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:71)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:58)
	at com.google.cloud.spanner.SpannerImpl$GrpcStreamIterator.computeNext(SpannerImpl.java:2122)
	at com.google.cloud.spanner.SpannerImpl$GrpcStreamIterator.computeNext(SpannerImpl.java:2068)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.cloud.spanner.SpannerImpl$ResumableStreamIterator.computeNext(SpannerImpl.java:2209)
	at com.google.cloud.spanner.SpannerImpl$ResumableStreamIterator.computeNext(SpannerImpl.java:2165)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.cloud.spanner.SpannerImpl$GrpcValueIterator.ensureReady(SpannerImpl.java:2358)
	at com.google.cloud.spanner.SpannerImpl$GrpcValueIterator.getMetadata(SpannerImpl.java:2331)
	at com.google.cloud.spanner.SpannerImpl$GrpcResultSet.next(SpannerImpl.java:1651)
	at com.google.cloud.spanner.ForwardingResultSet.next(ForwardingResultSet.java:34)
	at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.next(SessionPool.java:95)
	at com.google.cloud.spanner.it.ITQueryTest.analyzeProfile(ITQueryTest.java:604)
Caused by: com.google.cloud.spanner.SpannerException: INTERNAL: Invalid query plan.
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:43)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:80)
	at com.google.cloud.spanner.spi.v1.GrpcSpannerRpc$ResultSetStreamObserver.onError(GrpcSpannerRpc.java:520)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.spi.v1.WatchdogInterceptor$MonitoredCall$1.onClose(WatchdogInterceptor.java:190)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.GceTestEnvConfig$GrpcErrorInjector$1$1.onClose(GceTestEnvConfig.java:119)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid query plan.
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.spi.v1.WatchdogInterceptor$MonitoredCall$1.onClose(WatchdogInterceptor.java:190)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.GceTestEnvConfig$GrpcErrorInjector$1$1.onClose(GceTestEnvConfig.java:119)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

cc @vkedia

**Comment by garrettjonesgoogle** [comment]
Tests turned off in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2327 - resolving this issue now.
