### ISSUE TITLE
Impossible to publish message into a topic (using Google App Engine and Java) using Google PubSub

### ISSUE THREAD

**Issue by agsola** [GoogleCloudPlatform/google-cloud-java#2339]
I'm trying to make **Google PubSub** work, but it seems impossible.

I'm just trying to publish a message into a topic, with the code quite similar to this one:
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPublish.java

Something like this:
```
      Publisher publisher = null;
      String topicId = "mytopic";

      // create a publisher on the topic
      if (publisher == null) {
        publisher = Publisher.defaultBuilder(
            TopicName.create(ServiceOptions.getDefaultProjectId(), topicId))
            .build();
      }
      // construct a pubsub message from the payload
      final String payload = "mypayload";
      PubsubMessage pubsubMessage =
          PubsubMessage.newBuilder().setData(ByteString.copyFromUtf8(payload)).build();

      ApiFuture<String> messageId = publisher.publish(pubsubMessage);
```

After that, when accessing the Servlet it seems to work.
But I never get the message published.

Trying to see what happens, I add this code:

```
      resp.setContentType("text/plain");
      if (messageId != null) {
    	  	try {
				messageId.get();
				resp.getWriter().println("Eveything alrigth");
			} catch (InterruptedException e) {
				resp.getWriter().println("Exception InterruptedException:");
				resp.getWriter().println(e.toString());
				final StringWriter stacktrace = new StringWriter();
				e.printStackTrace(new PrintWriter(stacktrace));
				resp.getWriter().println(stacktrace.getBuffer());
			} catch (ExecutionException e) {
				resp.getWriter().println("Exception ExecutionException");
				resp.getWriter().println(e.toString());
				resp.getWriter().println(e.fillInStackTrace());
			}
      }
```

It takes quite a lot of seconds and finally I get this message:
```

Exception InterruptedException:
java.lang.InterruptedException
java.lang.InterruptedException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:473)
	at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:57)
	at com.myCompany.myClassName.doGet(myClassName.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:297)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:219)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:108)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:657)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:619)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:589)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:783)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
	at java.lang.Thread.run(Thread.java:745)

```

Any idea?

**Comment by agsola** [comment]
A few bits of information.

I'm using standard environment (not flexible) and my pom.xml includes (mainly) appengine, datastore and obviously Google PubSub.

**Comment by garrettjonesgoogle** [comment]
@agsola , Which runtime are you using - Java 7 or Java 8?

**Comment by agsola** [comment]
Java 8.

**Comment by lesv** [comment]
THis should be fixed.  Please reopen if you retest and it's not.

**Comment by AlbertoNitro** [comment]
I am having the same problem, please does anyone know how to solve it?
