### ISSUE TITLE
JUL LoggingHandler issues

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-java#2401]
There are a couple of issues in the `com.google.cloud.logging.LoggingHandler`

- Unused private methods: `getLoggingHandlers`, `hasLoggingHandler`
- Assigning the handler to a specific logger, rather than the root, doesn't work.
`com.example.handlers=com.google.cloud.logging.LoggingHandler`

The second one needs to be investigated a bit more.

@jabubake FYI

**Comment by jabubake** [comment]
Ran into this exception using the class-name handler, still investigating.
```
java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.grpc.ManagedChannelProvider.load(ManagedChannelProvider.java:63)
	at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:52)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:45)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:129)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
	at com.google.api.gax.grpc.ProviderManager.getChannel(ProviderManager.java:107)
	at com.google.api.gax.grpc.ChannelAndExecutor.create(ChannelAndExecutor.java:67)
	at com.google.api.gax.grpc.ClientSettings.getChannelAndExecutor(ClientSettings.java:77)
	at com.google.cloud.logging.spi.v2.ConfigClient.<init>(ConfigClient.java:131)
	at com.google.cloud.logging.spi.v2.ConfigClient.create(ConfigClient.java:122)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:116)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:64)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:58)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:435)
	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:134)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:108)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:426)
	at com.google.cloud.logging.LoggingHandler.getLogging(LoggingHandler.java:397)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:199)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:155)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:124)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.addLogger(LogManager.java:1165)
	at java.util.logging.LogManager.demandLogger(LogManager.java:556)
	at java.util.logging.Logger.demandLogger(Logger.java:455)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at com.example.flexible.logging.LoggingExample.<clinit>(LoggingExample.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2535)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1326)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1273)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:614)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:498)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:785)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:770)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:530)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pongad** [comment]
@jabubake @meltsufin  I just tried this a moment ago.

I set the config file to
```
com.example.handlers=com.google.cloud.logging.LoggingHandler
```

and ran Java code
```java
Logger logger = Logger.getLogger("com.example.foo.bar");
logger.info("YAY!!!");
```
Everything seems to work OK. Are you still experiencing the problems?

I'll send PR to delete private methods.

**Comment by meltsufin** [comment]
I don't think it's an issue anymore. We can close it for now.

**Comment by papudesi** [comment]
Upgrading our dependencies from grpc-core-1.7 to grpc-core-1.11.0, and grpc-netty-1.7.0 to grpc-netty-shaded-1.110, we get this exception:
```
Caused by: java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.ServiceProviders.load(ServiceProviders.java:42)
	at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:37)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:36)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:183)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:155)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:147)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:151)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:116)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:127)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:64)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:58)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:506)
	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:134)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:108)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:493)
	at com.google.cloud.logging.LoggingHandler.getLogging(LoggingHandler.java:360)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:195)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:151)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:120)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:563)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:506)
	at org.apache.juli.ClassLoaderLogManager$2.run(ClassLoaderLogManager.java:403)
	at org.apache.juli.ClassLoaderLogManager$2.run(ClassLoaderLogManager.java:399)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.juli.ClassLoaderLogManager.getClassLoaderInfo(ClassLoaderLogManager.java:399)
	at org.apache.juli.ClassLoaderLogManager.getLogger(ClassLoaderLogManager.java:230)
	at java.util.logging.LogManager.demandLogger(LogManager.java:551)
	at java.util.logging.Logger.demandLogger(Logger.java:455)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:67)
	at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:187)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:216)
	at org.apache.catalina.core.ContainerBase.getLogger(ContainerBase.java:360)
```

Also want to throw in that the root handler doesn't work for us, our logging.properties looks like this:
```
handlers = com.google.cloud.logging.LoggingHandler
.level = INFO

com.google.cloud.logging.LoggingHandler.level = INFO
com.google.cloud.logging.LoggingHandler.log = gae_app.log
com.google.cloud.logging.LoggingHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format = %3$s: %5$s%6$s

.handlers = com.google.cloud.logging.LoggingHandler
```

**Comment by garrettjonesgoogle** [comment]
@papudesi could you please open a new issue?

**Comment by papudesi** [comment]
@garrettjonesgoogle created #3219 and #3220, thanks.
