### ISSUE TITLE
Datastore - Datastore object creation fails with version 1.5.1

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#2440]
I'm trying to upgrade from version 1.2.3 of the Datastore API to the latest version, 1.5.1. The below sample code fails creating the Datastore object/service. 

```
Datastore datastore = DatastoreOptions.newBuilder().build().getService();
```

Tests are running on my laptop with gcloud installed. Version 1.2.3 works fine by fetching the defaults (e.g. project/credentials) from Google Cloud SDK. Version 1.5.1 is producing the below exception: 

```
Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 45: https://datastore.googleapis.com/v1/projects/<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1%2Fproject%2Fproject-id&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1%2Fproject%2Fproject-id&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>
	at com.google.datastore.v1.client.DatastoreFactory.validateUrl(DatastoreFactory.java:118)
	at com.google.datastore.v1.client.DatastoreFactory.buildProjectEndpoint(DatastoreFactory.java:104)
	at com.google.datastore.v1.client.DatastoreFactory.newRemoteRpc(DatastoreFactory.java:111)
	at com.google.datastore.v1.client.DatastoreFactory.create(DatastoreFactory.java:65)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.<init>(HttpDatastoreRpc.java:71)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreRpcFactory.create(DatastoreOptions.java:61)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreRpcFactory.create(DatastoreOptions.java:55)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:472)
	at com.google.cloud.datastore.DatastoreOptions.getDatastoreRpcV1(DatastoreOptions.java:179)
	at com.google.cloud.datastore.DatastoreImpl.<init>(DatastoreImpl.java:55)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreFactory.create(DatastoreOptions.java:51)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreFactory.create(DatastoreOptions.java:45)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:459)
	at com.jmethods.catatumbo.DatastoreTest.main(DatastoreTest.java:29)
Caused by: java.net.URISyntaxException: Illegal character in path at index 45: https://datastore.googleapis.com/v1/projects/<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1%2Fproject%2Fproject-id&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1%2Fproject%2Fproject-id&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at com.google.datastore.v1.client.DatastoreFactory.validateUrl(DatastoreFactory.java:116)
	... 13 more


```
I have traced it down to `ServiceOptions.getAppEngineProjectId` method where it tries to get the project ID from Metadata Server. Apparently, the http request executed by that method returns some string, and that string is assumed to be project ID. In my case, the default project ID is coming up as - 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1%2Fproject%2Fproject-id&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1%2Fproject%2Fproject-id&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>

```

Looks like this is an error from my Internet Service provider connecting to http://metadata.google.internal 

I do not have any environment variables such as `GOOGLE_*` set, and solely relying on the environment set up by the gcloud tool. Why is code running on my laptop trying to find the AppEngine project ID from the metadata server? Is anyone else experiencing this?

**Comment by sai-pullabhotla** [comment]
Running the same code with 1.5.1 on a different network/ISP works fine. The lookup of project ID from the Metadata Server fails as expected with - 

```
java.net.UnknownHostException: metadata.google.internal
```
and continues on with the subsequent searches - finds google cloud SDK's configuration file (`config_default`) and finds the correct project ID. 

Looks like this is an issue with some ISPs? My ISP at home is Cox and there we are getting a 200 OK response with some error text to indicate page not found for the URL http://metadata.google.internal/computeMetadata/v1/project/project-id, and the API is assuming that the error message is a project ID.

**Comment by sai-pullabhotla** [comment]
This is perhaps a classic example of DNS Hijacking by my ISP? Cox is listed on the page below. 

https://en.wikipedia.org/wiki/DNS_hijacking#Manipulation_by_ISPs

**Comment by sai-pullabhotla** [comment]
I changed my DNS at home to Google Public DNS and the issue is resolved. Not sure if there is anything that could be done in the API, like, check the returned string from the metadata server and make sure it is even a valid (length, the characters in the string, etc) project ID.

**Comment by neozwu** [comment]
@sai-pullabhotla Thanks for providing the detailed information.  Metadata server is the last resort to fetching project id (see code [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L389)). A recommended way is to explicitly set environment variable to project id.

**Comment by sai-pullabhotla** [comment]
@neozwu  - 

Technically speaking, fetching from gcloud settings is the last resort. In my specific case, there is a false positive from the metadata server lookup, which returns a huge HTML/JavaScript combination as the project ID. Instead of assuming it as a valid project ID, it would be nice to have some sanity check on the response to ensure it can possibly be a  project ID. For example, there might be something in the response header that could be validated (e.g. Server) or to ensure the response is a valid project ID based on its length and the characters in the string.  

For example - 
Project ID must be between 6 and 30 characters.
Project ID can have lowercase letters, digits or hyphens and must start with a lowercase letter. 

If these conditions evaluate to false, return null, so the code can continue with the next options.

**Comment by neozwu** [comment]
@sai-pullabhotla This indeed makes sense. I will label this as a P2 bug and will implement the validation logic.
/cc @lesv

**Comment by lesv** [comment]
**metadata.google.internal** should only be hit if you are running in the cloud.  The environment variables should be set that you aren't in production.

Production is true if any of these EnvVar's are set:

GAE_DEPLOYMENT_ID | 402856547336086879
GAE_ENV | standard
GAE_INSTANCE | 00c61b117c3c060e0818e8018dc0bd8dcb7397a6ca2c8ca943c2c677c170a95b93027639697422
USER | appengine
GAE_VERSION | gaeinfo:20170722t140621
GAE_RUNTIME | java8

That said, I would check the Java System Property:
`com.google.appengine.runtime.environment`  == `Production`  or  `Development`

If `Development`, don't try to hit `metadata.google.internal`

**Comment by hzyi-google** [comment]
@pongad I believe we decided not to check if we are running in the cloud [from this issue](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2683) since there aren't a way to decide if we are running on GCE unless we hit the metadata server. Does that apply to this issue as well?

**Comment by hzyi-google** [comment]
#2822  fixes this.

**Comment by wsh** [comment]
What @lesv describes here is true for App Engine, but not for GCE/GKE. Ideally we would fix this no matter where a user is running. @hzyi-google's work in validating the response from the metadata service is a good start. If we were to check [the Metadata-Flavor header](https://cloud.google.com/compute/docs/instances/managing-instances#runninggce) we could cover GCE cases easily, and for App Engine environments we shouldn't need to contact the metadata service for this information anyway (it's in the GOOGLE_CLOUD_PROJECT environmental variable, cf. b/64313434).
