### ISSUE TITLE
Cloud Pub/Sub Client Error when publishing data

### ISSUE THREAD

**Issue by munasinghecm** [GoogleCloudPlatform/google-cloud-java#2441]
0down votefavorite | I have followed following example that described Cloud PubSub (gRPC) with Android.https://github.com/rafaelsf80/cloud-pubsub-grpc-android. It works fine alone. But when I add the same code and dependencies to my existing project got following error.
-- | --

`09-15 11:36:14.812 31956-32764/com.example.stl.sciocardioapp E/art: Verification failed on class com.google.pubsub.v1.PubsubMessage$Builder in /data/data/com.example.stl.sciocardioapp/files/instant-run/dex/slice-grpc-pubsub-v1-0.0.2_df54ceb8a9a1043c6f69c84936a145dd371840e5-classes.dex because: Verifier rejected class com.google.pubsub.v1.PubsubMessage$Builder due to bad method com.google.pubsub.v1.PubsubMessage$Builder com.google.pubsub.v1.PubsubMessage$Builder.setPublishTime(com.google.protobuf.Timestamp)
09-15 11:36:14.812 31956-32764/com.example.stl.sciocardioapp E/ACRA: ACRA caught a RuntimeException for com.example.stl.sciocardioapp
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:304)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.VerifyError: Verifier rejected class com.google.pubsub.v1.PubsubMessage$Builder due to bad method com.google.pubsub.v1.PubsubMessage$Builder com.google.pubsub.v1.PubsubMessage$Builder.setPublishTime(com.google.protobuf.Timestamp) (declaration of 'com.google.pubsub.v1.PubsubMessage$Builder' appears in /data/data/com.example.stl.sciocardioapp/files/instant-run/dex/slice-grpc-pubsub-v1-0.0.2_df54ceb8a9a1043c6f69c84936a145dd371840e5-classes.dex)
    at com.google.pubsub.v1.PubsubMessage.toBuilder(PubsubMessage.java:382)
    at com.google.pubsub.v1.PubsubMessage.newBuilder(PubsubMessage.java:376)
    at com.stl.gcommunicator.PublishMessageTask.execute(PublishMessageTask.java:122)
    at serverconnection.DataUploadingService$Upload.doInBackground(DataUploadingService.java:183)
    at serverconnection.DataUploadingService$Upload.doInBackground(DataUploadingService.java:154)
    at android.os.AsyncTask$2.call(AsyncTask.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run`
Can someone help me to overcome with this problem

**Comment by andreamlin** [comment]
Can you provide more details?

**Comment by munasinghecm** [comment]
This error occurs due to the protobuf version conflict. In my project, I have already used 'com.google.protobuf:protobuf-java:3.2.0'
'com.google.protobuf:protobuf-java-util:3.2.0' 
dependencies.
But for the pubsub project, they asked to use 
'com.google.protobuf:protobuf-java:3.0.0-beta-1' dependency. 

As I observed this dependency mismatch cause for the error.

**Comment by andreamlin** [comment]
Ok, so just to be clear, this isn't an issue with google-cloud-java/google-cloud-pubsub, it's just a dependency mismatch? 

I'd suggest removing explicitly-defined dependencies on protobuf-java from your project, and just rely on the transitive dependencies from google-cloud-pubsub.
