### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.api.gax.rpc.ClientSettings when using Firestore

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-cloud-java#2496]
I'm seeing following test failures in my project when trying to use Firestore.

```
testServiceAccountProjectId(com.google.firebase.cloud.FirestoreClientTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/api/gax/rpc/ClientSettings
	at com.google.firebase.cloud.FirestoreClientTest.testServiceAccountProjectId(FirestoreClientTest.java:42)
Caused by: java.lang.ClassNotFoundException: com.google.api.gax.rpc.ClientSettings
	at com.google.firebase.cloud.FirestoreClientTest.testServiceAccountProjectId(FirestoreClientTest.java:42)

testAppDelete(com.google.firebase.cloud.FirestoreClientTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.firestore.FirestoreOptions
	at com.google.firebase.cloud.FirestoreClientTest.testAppDelete(FirestoreClientTest.java:56)

testExplicitProjectId(com.google.firebase.cloud.FirestoreClientTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.firestore.FirestoreOptions
	at com.google.firebase.cloud.FirestoreClientTest.testExplicitProjectId(FirestoreClientTest.java:30)
```

So far the solution seems to be adding the following as a dependency to my project:

```
      <dependency>
            <groupId>com.google.api</groupId>
            <artifactId>gax</artifactId>
            <version>1.8.1</version>
       </dependency>
```

Perhaps Firestore should declare this dependency explicitly.

**Comment by jabubake** [comment]
@hiranya911 : 
This sample works with just the Firestore dependency. 
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/firestore

Can you share your dependency tree ? Possible there's a conflict, requiring you to add this dependency explicitly.

**Comment by hiranya911** [comment]
```
[INFO] com.google.firebase:firebase-admin:jar:5.3.2-SNAPSHOT
[INFO] +- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |  \- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] +- com.google.api-client:google-api-client-gson:jar:1.22.0:compile
[INFO] |  \- com.google.http-client:google-http-client-gson:jar:1.22.0:compile
[INFO] |     \- com.google.code.gson:gson:jar:2.1:compile
[INFO] +- com.google.http-client:google-http-client:jar:1.22.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] +- com.google.api:api-common:jar:1.1.0:compile
[INFO] +- com.google.auth:google-auth-library-oauth2-http:jar:0.8.0:compile
[INFO] |  \- com.google.auth:google-auth-library-credentials:jar:0.8.0:compile
[INFO] +- com.google.cloud:google-cloud-storage:jar:1.2.1:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.2.1:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- com.google.api:gax:jar:1.4.1:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.3.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.12:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.12:compile
[INFO] |  +- com.google.cloud:google-cloud-core-http:jar:1.2.1:compile
[INFO] |  |  +- com.google.http-client:google-http-client-appengine:jar:1.21.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client-jackson:jar:1.21.0:compile
[INFO] |  |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  \- com.google.apis:google-api-services-storage:jar:v1-rev100-1.22.0:compile
[INFO] +- com.google.cloud:google-cloud-firestore:jar:0.25.0-beta:compile
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.7.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.3.1:compile
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.6.1:compile
[INFO] |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.6.1:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.6.1:compile
[INFO] |  +- com.google.api:gax-grpc:jar:0.25.1:compile
[INFO] |  |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  |  \- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-firestore-v1beta1:jar:0.1.20:compile
[INFO] |  +- io.grpc:grpc-netty:jar:1.6.1:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.6.1:compile (version selected from constraint [1.6.1,1.6.1])
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.19:compile
[INFO] |  |  |  +- com.google.instrumentation:instrumentation-api:jar:0.4.3:compile
[INFO] |  |  |  \- io.opencensus:opencensus-api:jar:0.5.1:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.14.Final:compile (version selected from constraint [4.1.14.Final,4.1.14.Final])
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.14.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec:jar:4.1.14.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler:jar:4.1.14.Final:compile
[INFO] |  |  |     \- io.netty:netty-buffer:jar:4.1.14.Final:compile
[INFO] |  |  |        \- io.netty:netty-common:jar:4.1.14.Final:compile
[INFO] |  |  \- io.netty:netty-handler-proxy:jar:4.1.14.Final:compile
[INFO] |  |     +- io.netty:netty-transport:jar:4.1.14.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver:jar:4.1.14.Final:compile
[INFO] |  |     \- io.netty:netty-codec-socks:jar:4.1.14.Final:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.6.1:compile
[INFO] |  \- io.grpc:grpc-auth:jar:1.6.1:compile
[INFO] +- com.google.guava:guava:jar:20.0:compile
[INFO] +- org.json:json:jar:20160810:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.mockito:mockito-core:jar:2.7.21:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.6.11:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.6.11:test
[INFO] |  \- org.objenesis:objenesis:jar:2.5:test
[INFO] +- net.java.quickcheck:quickcheck:jar:0.6:test
[INFO] |  \- net.java.quickcheck:quickcheck-src-generator:jar:0.6:test
[INFO] +- com.cedarsoftware:java-util:jar:1.26.0:test
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.5:test
[INFO] |  \- org.apache.logging.log4j:log4j-core:jar:2.5:test
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```

It looks like due to the old version of google-cloud-storage, which pulls in an older version of gax. I'll try upgrading.

**Comment by hiranya911** [comment]
GCS upgrade is working for me. Closing the issue.

**Comment by AraujoArquivei** [comment]
I'm having a similar problem. 

My pipeline presets problems on executing queries. Which is done based in a class of mine. Basically, he initiates, but can't proceed. 

[exception.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1591976/exception.txt)

this is my pom.xml:

[pom.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1591985/pom.txt)

and, finally, my class: 

[Class.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1591990/Class.txt)

**Comment by AnkushNakaskar** [comment]
After adding 
	compile group: 'com.google.api', name: 'gax', version: '1.8.1'

I am getting error with 
ClassNotFoundException: com.google.api.gax.rpc.HeaderProvider

**Comment by charbull** [comment]
Any luck with this?
