### ISSUE TITLE
table.load doesn't work for local files

### ISSUE THREAD

**Issue by bootstraponline** [GoogleCloudPlatform/google-cloud-java#2567]
BigQuery `table.load` in Ruby works for local files. Java BigQuery requires a GCS URI. Is there a reason why local file loading isn't supported?

```ruby
# Ruby
def load_job(table_obj, rows)
  Tempfile.create(['tmp', '.json']) do |json_file|
    json_file.write rows.map(&:to_json).join("\n")
    json_file.rewind

    puts "Uploading:\n #{File.read(json_file)}"

    validate_table(table_obj)
    job = table_obj.load(json_file,
                          format: 'JSON',
                          create: 'never',
                          write:  'append')

    wait_for_job job
  end
end
```

```java
// Java
val loadJob = table.load(FormatOptions.json(), jsonFile.canonicalPath)
loadJob.waitFor(RetryOption.totalTimeout(Duration.ofMinutes(20)))
```

```
Exception in thread "main" com.google.cloud.bigquery.BigQueryException: Source URI must be a Google Cloud Storage location: /private/var/folders/14/h2zk5sx1315b__blzdt7hz1m4k0by8/T/build255306573373834232.json
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:84)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:168)
	at com.google.cloud.bigquery.BigQueryImpl$3.call(BigQueryImpl.java:208)
	at com.google.cloud.bigquery.BigQueryImpl$3.call(BigQueryImpl.java:205)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:91)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:205)
	at com.google.cloud.bigquery.Table.load(Table.java:517)
	at com.google.cloud.bigquery.Table.load(Table.java:479)
	at bigquery.BitriseQuery.updateData(BitriseQuery.kt:26)
	at tasks.UpdateBigQueryKt.main(UpdateBigQuery.kt:11)
```

**Comment by anthmgoogle** [comment]
@vam-google can you confirm whether or not there is a way to do this in the current API. If not, let's change this from question to feature request and it can be evaluated in the next round of feature planning.

**Comment by pongad** [comment]
Loading from the machine does work. It is in [`table.insert`](https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/index.html?com/google/cloud/bigquery/package-summary.html). It does not handle JSON though and you need to create rows explicitly.

One way to help with this is creating a json->Iterable<RowToInsert> converter. I've added this to [feature wiki](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog), so I'll close this for now.
