### ISSUE TITLE
NoSuchMethodError while using cloud pubsub java client

### ISSUE THREAD

**Issue by smileprem** [GoogleCloudPlatform/google-cloud-java#2710]
Hi - I am new to GCP. I am trying to integrate java app with cloud pubsub emulator. I use java 8 on Windows 10 machine. I simply added the below dependency to pom and ran the example program `CreateSubscriptionAndConsumeMessages`.

```
<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-pubsub</artifactId>
            <version>0.32.0-beta</version>
        </dependency>
```
I get the below error. Shouldn't all the dependencies be managed by google java client?. If there are exceptions, please document it.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfInstanceOf(Ljava/lang/Throwable;Ljava/lang/Class;)V
	at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:56)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.pubsub.v1.SubscriptionAdminClient.createSubscription(SubscriptionAdminClient.java:282)
	at com.google.cloud.pubsub.v1.SubscriptionAdminClient.createSubscription(SubscriptionAdminClient.java:250)
	at io.flux.modelservice.subscribers.CreateSubscriptionAndConsumeMessages.main(CreateSubscriptionAndConsumeMessages.java:24)

```

**Comment by smileprem** [comment]
```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>
```
Adding the guava dependency solved the issue. Please include in the pom or explicitly document it.

**Comment by garrettjonesgoogle** [comment]
Guava should already be pulled in as a dependency. I suspect your build system was choosing a version of Guava that was too old, and when you added version 21.0, you got an updated one that worked correctly with google-cloud.

**Comment by smileprem** [comment]
Hi @garrettjonesgoogle - You are right. It was actually a dependency resolution issue when Cloud PubSub is used along with Janus Graph. JanusGraph pulls Guava version 16.0. But GCP needs version 20.0 (minimum). So, I excluded Guava from JanusGraph dependency and let GCP Client pull the latest guava dependency.

It works !!!

```
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-core</artifactId>
            <version>${janusgraph.version}</version>
            <exclusions>
                <!-- JanusGraph uses version 16.0, but GCP needs version 20.0 -->
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-integration-gcp</artifactId>
            <version>${spring-cloud-gcp.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
            <version>${spring-cloud-gcp.version}</version>
        </dependency>
```
