### ISSUE TITLE
Bigquery 0.32.0-beta - Needs new guava version

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/google-cloud-java#2804]
Getting the following error w/bigquery 0.32.0-beta when doing dataset.exists()

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.cloud.bigquery.BigQueryImpl.optionMap(BigQueryImpl.java:684)
	at com.google.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:224)
	at com.google.cloud.bigquery.Dataset.exists(Dataset.java:174)
```

**Comment by garrettjonesgoogle** [comment]
Which version of Guava is your dependency tree resolving to?

**Comment by cobookman** [comment]
Not sure how to check. But adding this to my `pom.xml` resolved the error:

```
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.6-jre</version>
    </dependency>
```

Let me know what maven commands to run and I'll run them.

**Comment by garrettjonesgoogle** [comment]
Well I was going to see if you had 19.0 or earlier and suggest a higher version if so, but it looks like a higher version already solved your problem.

For maven, I like to use:

```mvn dependency:tree```

**Comment by garrettjonesgoogle** [comment]
Closing out issue because the filer's problem is resolved.
