### ISSUE TITLE
ProviderNotFoundException while using Pub/Sub and BigTanle on DataProc

### ISSUE THREAD

**Issue by nicolasoge** [GoogleCloudPlatform/google-cloud-java#2810]
Hi everybody,

I am trying to build an application with both Pub/Sub and BigTable on top of Dataproc cluster with Spark.

However while connecting to BigTable, this line throw an exception:
`BigtableConfiguration.connect(projectId, instanceId)`

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at mycompany.batch.SinglePredictorBatchLauncher.main(SinglePredictorBatchLauncher.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalStateException: Could not find an appropriate constructor for my_conf.cloud.bigtable.hbase1_x.BigtableConnection
        at my_conf.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:114)
        at my_conf.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:99)
        at mycompany.util.app.EbapContext$.hBaseRuntime$lzycompute(EbapContext.scala:57)
        at mycompany.util.app.EbapContext$.hBaseRuntime(EbapContext.scala:44)
        at mycompany.util.app.HBaseSupport$class.$init$(HBaseSupport.scala:4)
        at mycompany.batch.SinglePredictorBatchLauncher$.<init>(SinglePredictorBatchLauncher.scala:10)
        at mycompany.batch.SinglePredictorBatchLauncher$.<clinit>(SinglePredictorBatchLauncher.scala)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at my_conf.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:111)
        ... 16 more
Caused by: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact
        at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:124)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:36)
        at my_conf.cloud.bigtable.grpc.BigtableSession.createNettyChannel(BigtableSession.java:471)
        at my_conf.cloud.bigtable.grpc.BigtableSession$3.create(BigtableSession.java:398)
        at my_conf.cloud.bigtable.grpc.io.ChannelPool.<init>(ChannelPool.java:246)
        at my_conf.cloud.bigtable.grpc.BigtableSession.createChannelPool(BigtableSession.java:401)
        at my_conf.cloud.bigtable.grpc.BigtableSession.createManagedPool(BigtableSession.java:413)
        at my_conf.cloud.bigtable.grpc.BigtableSession.getDataChannelPool(BigtableSession.java:276)
        at my_conf.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:236)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:143)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:110)
        at my_conf.cloud.bigtable.hbase1_x.BigtableConnection.<init>(BigtableConnection.java:53)
        ... 21 more
```

My SBT dependencies are listed below:
```
"com.google.cloud" % "google-cloud-storage" % "1.15.0"
"com.google.cloud.bigtable" % "bigtable-hbase-1.x" % "1.0.0" exclude("io.netty","netty-tcnative-boringssl-static")
"com.google.apis" % "google-api-services-dataproc" % "v1-rev69-1.23.0"
"com.google.cloud" % "google-cloud-pubsub" % "0.33.0-beta"
```

and assembly rules:
```
val settings = Seq(
    assemblyMergeStrategy in assembly := {
      case PathList("META-INF", xs @ _*) =>
        xs map {_.toLowerCase} match {
          case "native" :: _ =>
            MergeStrategy.first
          case _ => MergeStrategy.discard
        }
      case "reference.conf" => MergeStrategy.concat
      case x => MergeStrategy.first
    },
    assemblyShadeRules in assembly := Seq(
      ShadeRule.rename("com.google.**" -> "my_conf.@1").inAll,
      ShadeRule.rename("io.netty.**" -> "my_conf2.@1").inAll
  )
  )
```

The first strange thing is that `grpc-netty-1.7.0` is on the classpath.
The second one is that my code runs perfectly well locally, on top of the spark standalone node on my dev machine.

I have tried to remove the netty jar located in `/usr/lib/hadoop/lib` at cluster creation with the initialization action option but it still does not work for me.

I have tried different shading options with no working configuration.

Thanks for your help

**Comment by garrettjonesgoogle** [comment]
Try using grpc 1.9 instead - you might have a problem with tcnative, which in 1.9 is shaded into grpc itself.

**Comment by nicolasoge** [comment]
Thanks for your reply.
The exception is still there with gRPC 1.9.
In fact I have already been testing with 1.9 as it comes with pubsub 0.33.
I had just updated from 0.32 to 0.33 before writing this issue, and forgot to update the gRPC version from 1.7 to 1.9.

Thanks for your help

**Comment by nicolasoge** [comment]
Could it be related to my fat-jar assembling `META-INF` discard policy ?
With another policy (keep first) I get another error message:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at my_company.batch.SinglePredictorBatchLauncher.main(SinglePredictorBatchLauncher.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalStateException: Could not find an appropriate constructor for my_conf.cloud.bigtable.hbase1_x.BigtableConnection
        at my_conf.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:114)
        at my_conf.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:99)
        at my_company.util.app.EbapContext$.hBaseRuntime$lzycompute(EbapContext.scala:57)
        at my_company.util.app.EbapContext$.hBaseRuntime(EbapContext.scala:44)
        at my_company.util.app.HBaseSupport$class.$init$(HBaseSupport.scala:4)
        at my_company.batch.SinglePredictorBatchLauncher$.<init>(SinglePredictorBatchLauncher.scala:10)
        at my_company.batch.SinglePredictorBatchLauncher$.<clinit>(SinglePredictorBatchLauncher.scala)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at my_conf.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:111)
        ... 16 more
Caused by: java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
        at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:163)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:546)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:539)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:477)
        at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:325)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:342)
        at my_conf.cloud.bigtable.grpc.BigtableSession.createNettyChannel(BigtableSession.java:483)
        at my_conf.cloud.bigtable.grpc.BigtableSession$3.create(BigtableSession.java:398)
        at my_conf.cloud.bigtable.grpc.io.ChannelPool.<init>(ChannelPool.java:246)
        at my_conf.cloud.bigtable.grpc.BigtableSession.createChannelPool(BigtableSession.java:401)
        at my_conf.cloud.bigtable.grpc.BigtableSession.createManagedPool(BigtableSession.java:413)
        at my_conf.cloud.bigtable.grpc.BigtableSession.getDataChannelPool(BigtableSession.java:276)
        at my_conf.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:236)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:143)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:110)
        at my_conf.cloud.bigtable.hbase1_x.BigtableConnection.<init>(BigtableConnection.java:53)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:34)
        at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
        ... 39 more
```

Thanks for your help

**Comment by sduskis** [comment]
On the Bigtable side, use `bigtable-hbase-1.x-hadoop` instead of `bigtable-hbase-1.x`

**Comment by sduskis** [comment]
Here's a bit more information on the Cloud Bigtable artifact.  Hadoop and Spark have different versions of guava, protobuf and netty than grpc.  That causes major "diamond dependency" problem between any gcp grpc client and the Big Data framework.  Cloud Bigtable gets around this problem by shading and repackaging the dependencies in question in the `bigtable-hbase-1.x-hadoop` artifact.

I don't know if Pub/Sub has the same type of problem with Spark.

**Comment by sduskis** [comment]
@garrettjonesgoogle, FYI, this is a "diamond dependency" problem related issue.

**Comment by nicolasoge** [comment]
Thanks for your help.

I had already tested with both the `bigtable-hbase-1.x-hadoop` and `bigtable-hbase-1.x-shaded` version of bigtable client and had the same issue.

I have not found any shaded version of Pub/Sub client.

Thanks for your help

**Comment by igorbernstein2** [comment]
I'm a little concerned about your assembly rules:
```
 assemblyShadeRules in assembly := Seq(
      ShadeRule.rename("com.google.**" -> "my_conf.@1").inAll,
      ShadeRule.rename("io.netty.**" -> "my_conf2.@1").inAll
  )
```
Renaming netty is non-trivial due to thenative jni libs shippped in tcnative. Please remove the netty rename. Instead try this:

1. Provide us with a dependency graph using something like https://github.com/jrudolph/sbt-dependency-graph
2. netty, tcnative & grpc-netty from the com.google.cloud.* dependencies
3. add io.grpc:grpc-netty-shaded as a dependency

Also, for gathering knowledge for the future, would you mind telling me if you get the same error with  bigtable-hbase-1.x-hadoop without the renames and without the other google clients?

Thanks!

**Comment by pongad** [comment]
Looks like issue persists, similar to #2813. I'll reopen.

**Comment by pongad** [comment]
@igorbernstein2 Is there any action item for this beyond moving to `netty-grpc-shaded` that's already tracked in #2813? If not, can we resolve this as dup?

**Comment by igorbernstein2** [comment]
Nope, can be closed
