### ISSUE TITLE
Compatibility Issue with Play 2.5.9

### ISSUE THREAD

**Issue by playtowork** [GoogleCloudPlatform/google-cloud-java#2813]
I have a Play framework project (version 2.5.9).

I append the following in its `build.sbt`'s `libraryDependencies`:
"com.google.cloud"        % "google-cloud-vision"      % "1.15.0"

Then I run `sbt clean && sbt "project frontend" run`. Instead of the app starting, it errors with the following:

--- (Running the application, auto-reloading is enabled) ---

java.lang.NoSuchFieldError: DEFAULT_MAX_PENDING_TASKS
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at play.core.server.NettyServer.<init>(NettyServer.scala:77)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:235)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:64)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:54)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last frontend/compile:run for the full output.
[error] (frontend/compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 77 s, completed Jan 28, 2018 1:05:10 PM

**Comment by pongad** [comment]
@garrettjonesgoogle Looks like problem with Netty dependencies. IIUC, we need to change from `grpc-netty` to `grpc-netty-shaded` right? I *think* we need to change this in gax too?

**Comment by playtowork** [comment]
FYI, I also tried adding this library to the dependencies for a Play framework (version 2.6.10) project. It had the same issue.

**Comment by garrettjonesgoogle** [comment]
Looks like we need to make the switch to `grpc-netty-shaded` everywhere.

**Comment by playtowork** [comment]
Cool. What's the ETA for fixing this bug? Would I have to wait to consume the next minor version release?

**Comment by pongad** [comment]
We're working on this in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2832. You have to wait for next release though, unless you want to build it from source.
