### ISSUE TITLE
Table-valued functions are not supported when SQL query which has JS based function

### ISSUE THREAD

**Issue by sabarivs** [GoogleCloudPlatform/google-cloud-java#2893]
Hi Team,
         I have included the below dependency in my java app
**<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-bigquery</artifactId>
  <version>0.34.0-beta</version>
</dependency>**

i am trying to execute below sql 

**SELECT COUNT(*) as adj_count, adjective
FROM 
 JS(
 (SELECT tokens FROM pcf_sb_1_1517930560980472067.pcf_gcp_twitter_ds_table ),
 tokens,
 "[{ name:'adjective', type: 'string'}]",
 "function(row, emit) { 
   try {
     x = JSON.parse(row.tokens);
     x.forEach(function(token) {
       if (token.partOfSpeech.tag === 'ADJ') {
         emit({ adjective: token.lemma.toLowerCase() });
       }
     });
   } catch (e) {}
 }" 
 )
GROUP BY adjective
ORDER BY adj_count DESC
LIMIT 100**

I am getting below exception when i executed the above query,

**Exception in thread "main" com.google.cloud.bigquery.BigQueryException: Table-valued functions are not supported at [3:2]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:98)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:393)
	at com.google.cloud.bigquery.BigQueryImpl$22.call(BigQueryImpl.java:617)
	at com.google.cloud.bigquery.BigQueryImpl$22.call(BigQueryImpl.java:614)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:614)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:606)
	at com.google.cloud.bigquery.Job$1.call(Job.java:325)
	at com.google.cloud.bigquery.Job$1.call(Job.java:322)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.poll(RetryHelper.java:63)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:321)
	at com.google.cloud.bigquery.Job.waitFor(Job.java:240)
	at com.cts.tweet.analysis.SimpleApp.main(SimpleApp.java:86)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "query",
    "locationType" : "other",
    "message" : "Table-valued functions are not supported at [3:2]",
    "reason" : "invalidQuery"
  } ],
  "message" : "Table-valued functions are not supported at [3:2]"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:391)
	... 15 more**

	I was able to execute normal SQL query using above dependency but not able to execute it above mentioned SQL..

	Please clarify this issue.

**Comment by pongad** [comment]
@tswast This looks like https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3606. Can you comment?

**Comment by tswast** [comment]
@sabarivs Are you able to execute this SQL from the web interface, but not the Java client?

The BigQuery client library uses standard SQL syntax by default. I believe the SQL you provided is using legacy SQL syntax.

Standard SQL syntax for UDFs is documented at https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions

Alternatively, you can set the query syntax to legacy SQL with

```
      QueryJobConfiguration.newBuilder(queryString)
          // To use standard SQL syntax, set useLegacySql to false. See:
          // https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql
          .setUseLegacySql(true)
          .build();
```

**Comment by sabarivs** [comment]
@tswast  i set the query syntax to use legacy sql as you suggested and was able to get response without exception. thanks for your support.
