### ISSUE TITLE
Compute API: NPE in StorageImageConfiguration

### ISSUE THREAD

**Issue by dtretyakov** [GoogleCloudPlatform/google-cloud-java#2973]
Steps to reproduce:
* Execute `compute.listImages().iterateAll()`

It throws the following exception:
```java
java.lang.NullPointerException
        at com.google.cloud.compute.StorageImageConfiguration$Builder.<init>(StorageImageConfiguration.java:69)
        at com.google.cloud.compute.StorageImageConfiguration$Builder.<init>(StorageImageConfiguration.java:49)
        at com.google.cloud.compute.StorageImageConfiguration.fromPb(StorageImageConfiguration.java:202)
        at com.google.cloud.compute.ImageConfiguration.fromPb(ImageConfiguration.java:188)
        at com.google.cloud.compute.ImageInfo$BuilderImpl.<init>(ImageInfo.java:172)
        at com.google.cloud.compute.Image.fromPb(Image.java:212)
        at com.google.cloud.compute.ComputeImpl$40.apply(ComputeImpl.java:1259)
        at com.google.cloud.compute.ComputeImpl$40.apply(ComputeImpl.java:1256)
        at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at jetbrains.buildServer.clouds.google.connector.GoogleApiConnectorImpl$getImagesAsync$1.doResume(GoogleApiConnectorImpl.kt:312)
```

According to java docs `com.google.api.services.compute.model.Image#getRawDisk` could return null, so it's not safe to execute `imagePb.getRawDisk().getContainerType() != null`:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/StorageImageConfiguration.java#L69-L73

Originally from: https://youtrack.jetbrains.com/issue/TW-53938

**Comment by hzyi-google** [comment]
According to this [compute doc](https://cloud.google.com/compute/docs/reference/rest/v1/images#insert) compute now supports creating images from four sources: rawDisk.source, sourceDisk, sourceImage and sourceSnapshot. IIUC the compute client library does not support the latter two for the moment. From the conversation in [here]( https://youtrack.jetbrains.com/issue/TW-53938) it seems the user is using sourceImage to create an image. 
We should probably make it a feature request since it's relatively non-granular work. @garrettjonesgoogle @pongad Any thoughts?

**Comment by garrettjonesgoogle** [comment]
We shouldn't do any feature work on this client since it's going to be replaced by a new auto-generated client soon.

**Comment by pongad** [comment]
I cannot seem to open the linked page. If the work is non-granular, I agree with @garrettjonesgoogle that we should wait for this to be replaced by auto-generated client.

**Comment by hzyi-google** [comment]
Thanks @garrettjonesgoogle @pongad let's leave this issue open until the client is replaced by the new auto-generated client. 

BTW the link is the same as the last link in @dtretyakov 's comment. It seems down.

**Comment by hzyi-google** [comment]
The new [compute library](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1) is generated.
