### ISSUE TITLE
Bigquery com.google.api.gax.retrying.PollException

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-java#3122]
I have an App Engine Standard project, which is performing query jobs on BigQuery

This is the library version
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-bigquery</artifactId>
    <version>1.24.0</version>
</dependency>
```

This is the code
```
RetryOption retryOption = RetryOption.totalTimeout(Duration.ofMillis(60000));
Job waitedJob;
try {
    waitedJob = job.waitFor(retryOption);
} catch (InterruptedException e) {
    throw new IOException(e);
}
```

I got this error on `waitFor` method call, but I'm unable to understand the cause
```
com.google.cloud.bigquery.BigQueryException: com.google.api.gax.retrying.PollException
	at com.google.cloud.bigquery.BigQueryException.translateAndThrow(BigQueryException.java:108)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:337)
	at com.google.cloud.bigquery.Job.waitFor(Job.java:240)
	<stacktrace of my classes>
Caused by: com.google.api.gax.retrying.PollException
	at com.google.api.gax.retrying.ExponentialPollAlgorithm.shouldRetry(ExponentialPollAlgorithm.java:68)
	at com.google.api.gax.retrying.RetryAlgorithm.shouldRetry(RetryAlgorithm.java:115)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:151)
	at com.google.api.gax.retrying.BasicRetryingFuture.setAttemptFuture(BasicRetryingFuture.java:87)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:90)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.poll(RetryHelper.java:63)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:321)
```

**Comment by pongad** [comment]
@NicolaSpreafico I think this is caused by a timeout: the operation didn't complete in 1 min. We should probably make this more clear though.

**Comment by NicolaSpreafico** [comment]
Thank you, after seeing logs I think you are right.

Job started: 2018-04-03 18:00:06.199
Error thrown: 2018-04-03 18:01:12.490

This job perform a query on a Google Spreadsheet federated source, so maybe sometimes can take longer than 1 minute to access data. I will now raise the timeout for avoid future problems
