### ISSUE TITLE
google-cloud-pubsub 0.21.0-beta: `RejectedExecutionException` when publishing new messages

### ISSUE THREAD

**Issue by stianlagstad** [GoogleCloudPlatform/google-cloud-java#3145]
We're seeing exceptions from `com.google.cloud.pubsub.v1.Publisher.publish` when trying to publish many messages quickly.

```
Critical error in message receiver java.util.concurrent.RejectedExecutionException:
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3dca33bb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7977292c[Terminated, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 11555] at 
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) at 
java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) at 
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) at 
java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) at 
java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729) at 
com.google.cloud.pubsub.v1.Publisher.setupDurationBasedPublishAlarm(Publisher.java:277) at 
com.google.cloud.pubsub.v1.Publisher.publish(Publisher.java:229) at 
com.cognite.purgatory.services.PipelineService.pushMessagesWithExplicitPipelineId(PipelineService.java:209) at 
com.cognite.purgatory.services.PipelineService.notifyPipelines(PipelineService.java:174) at 
com.cognite.purgatory.services.PipelineService.process(PipelineService.java:106) at 
com.cognite.purgatory.handlers.PurgatoryJobHandler.handleV1(PurgatoryJobHandler.java:25) at 
com.cognite.purgatory.handlers.PurgatoryJobHandler.handle(PurgatoryJobHandler.java:19) at 
com.cognite.purgatory.App.lambda$setUpListener$0(App.java:94) at 
com.cognite.pubsub.PubsubListener.handleMessage(PubsubListener.java:108) at 
com.cognite.pubsub.PubsubListener.lambda$getMessageReceiver$0(PubsubListener.java:90) at 
com.google.cloud.pubsub.v1.MessageDispatcher$2.run(MessageDispatcher.java:409) at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at 
java.util.concurrent.FutureTask.run(FutureTask.java:266) at 
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at 
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at 
java.lang.Thread.run(Thread.java:748)
```
which I believe comes from:
```
An exception was thrown by io.grpc.netty.NettyClientHandler$3.operationComplete() java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@15477b52 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7977292c[Shutting down, pool size = 19, active threads = 0, queued tasks = 0, completed tasks = 11555] at 
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) at 
java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) at 
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) at 
java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) at 
java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) at 
java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) at 
io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:77) at 
io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:70) at 
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.onReady(ClientCallImpl.java:584) at 
io.grpc.internal.DelayedStream$DelayedStreamListener.onReady(DelayedStream.java:392) at 
io.grpc.internal.AbstractStream$TransportState.notifyIfReady(AbstractStream.java:282) at 
io.grpc.internal.AbstractStream$TransportState.onStreamAllocated(AbstractStream.java:225) at 
io.grpc.netty.NettyClientStream$TransportState.setHttp2Stream(NettyClientStream.java:232) at 
io.grpc.netty.NettyClientHandler$3.operationComplete(NettyClientHandler.java:469) at 
io.grpc.netty.NettyClientHandler$3.operationComplete(NettyClientHandler.java:457) at 
io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) at 
io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) at 
io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) at 
io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) at 
io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:389) at 
io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:355) at 
io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:267) at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) at 
io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:52) at 
io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) at 
io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500) at 
io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479) at 
io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) at 
io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) at 
io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) at 
io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:673) at 
io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:257) at 
io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:337) at 
io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:419) at 
io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) at 
io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362) at 
io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901) at 
io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1321) at 
io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) at 
io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) at 
io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:1667) at 
io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:735) at 
io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712) at 
io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) at 
io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) at 
io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:201) at 
io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) at 
io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) at 
io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) at 
io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:983) at 
io.netty.channel.AbstractChannel.flush(AbstractChannel.java:248) at 
io.grpc.netty.WriteQueue.flush(WriteQueue.java:136) at 
io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32) at 
io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44) at 
io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at 
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) at 
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) at 
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at 
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) at 
java.lang.Thread.run(Thread.java:748)
```

In addition, we're also seeing this one:
```
RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@340c6ca9 with executor MoreExecutors.directExecutor() java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@658bcc5e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@61667ce5[Shutting down, pool size = 6, active threads = 1, queued tasks = 40, completed tasks = 1217] at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) at 
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) at 
java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) at 
java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729) at 
com.google.cloud.pubsub.v1.MessageDispatcher.setupPendingAcksAlarm(MessageDispatcher.java:426) at 
com.google.cloud.pubsub.v1.MessageDispatcher.access$500(MessageDispatcher.java:55) at 
com.google.cloud.pubsub.v1.MessageDispatcher$AckHandler.onSuccess(MessageDispatcher.java:223) at 
com.google.cloud.pubsub.v1.MessageDispatcher$AckHandler.onSuccess(MessageDispatcher.java:172) at 
com.google.common.util.concurrent.Futures$4.run(Futures.java:1135) at 
com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at 
com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902) at 
com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813) at 
com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:655) at 
com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:48) at 
com.google.cloud.pubsub.v1.MessageDispatcher$1.nack(MessageDispatcher.java:400) at 
com.cognite.pubsub.PubsubListener.lambda$getMessageReceiver$0(PubsubListener.java:95) at 
com.google.cloud.pubsub.v1.MessageDispatcher$2.run(MessageDispatcher.java:409) at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at 
java.util.concurrent.FutureTask.run(FutureTask.java:266) at 
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at 
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```

I just realized that version `0.43.0-beta` is out, but the code dealing with executorprovider doesn't look to be changed since `0.21.0-beta`. Is the right solution here just to provide our own `ExecutorProvider` with a higher thread count?

**Comment by stianlagstad** [comment]
Sorry, this was not caused by the fact that messages were created too fast. This was caused by kubernetes shutting down our application and thus shutting down the executor. Sorry about the noise.
