### ISSUE TITLE
com.google.cloud:google-cloud-core:jar:tests:1.27.1

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#3198]
Locally at master I'm seeing:

```
[ERROR] Failed to execute goal on project google-cloud-bigtable: Could not resolve dependencies for project com.google.cloud:google-cloud-bigtable:jar:0.45.1-alpha-SNAPSHOT: Could not find artifact com.google.cloud:google-cloud-core:jar:tests:1.27.1-SNAPSHOT -> [Help 1]
[ERROR] 
```

Looks like an artifact that isn't in Maven Central yet? Can anyone suggest how I should proceed?

**Comment by elharo** [comment]
Are their instructions for this somewhere? My efforts to build google-cloud-core in isolation hit other errors.

**Comment by elharo** [comment]
FYI it looks like I need to pre-install google-cloud-bom & google-cloud-core but not google-cloud-core-grpc. I also need to run 

```
$ gcloud components install bigtable
 ```

**Comment by elharo** [comment]
BigTable tests are failing. Is there some additional setup for this?

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.154 sec <<< FAILURE! - in com.google.cloud.bigtable.data.v2.it.ReadModifyWriteIT
test(com.google.cloud.bigtable.data.v2.it.ReadModifyWriteIT)  Time elapsed: 0.154 sec  <<< FAILURE!
java.lang.AssertionError: Not true that <<ByteString@6c696fc size=8>> is equal to <<ByteString@7f43c4d8 size=1>>
	at com.google.cloud.bigtable.data.v2.it.ReadModifyWriteIT.test(ReadModifyWriteIT.java:53)
Caused by: java.lang.AssertionError: Not true that <<ByteString@6c696fc size=8>> is equal to <<ByteString@7f43c4d8 size=1>>
	at com.google.cloud.bigtable.data.v2.it.ReadModifyWriteIT.test(ReadModifyWriteIT.java:53)
```

**Comment by garrettjonesgoogle** [comment]
@igorbernstein2 do you have any insight into the test failure that @elharo is seeing here? (Note: integration tests seem to be working on master fine)

**Comment by igorbernstein2** [comment]
I haven't been able to replicate this on linux nor os x.

@elharo, can you share some more details about your setup?
- The output of `mvn -version`
- The output of `gcloud components list --format=json`
- The output of `git rev-parse HEAD`
- The output of `git status`
- The exact command that you used to start the integration tests

Thanks

**Comment by elharo** [comment]
```
$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
```

**Comment by elharo** [comment]
```
$ gcloud components list --format=json

Your current Cloud SDK version is: 199.0.0
The latest available version is: 199.0.0

[
  {
    "current_version_string": null,
    "id": "app-engine-go",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "App Engine Go Extensions",
    "size": 158700261,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "cbt",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "Cloud Bigtable Command Line Tool",
    "size": 4874944,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "datalab",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "20180412",
    "name": "Cloud Datalab Command Line Tool",
    "size": 63004,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "cloud-datastore-emulator",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "1.4.1",
    "name": "Cloud Datastore Emulator",
    "size": 18730660,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "gcd-emulator",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "v1beta3-1.0.0",
    "name": "Cloud Datastore Emulator (Legacy)",
    "size": 39934155,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "pubsub-emulator",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "2018.02.02",
    "name": "Cloud Pub/Sub Emulator",
    "size": 35064941,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "emulator-reverse-proxy",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "Emulator Reverse Proxy",
    "size": 15162435,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "container-builder-local",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "Google Container Local Builder",
    "size": 4554646,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "docker-credential-gcr",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "Google Container Registry's Docker credential helper",
    "size": 2581163,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "alpha",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "2017.09.15",
    "name": "gcloud Alpha Commands",
    "size": 691,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": null,
    "id": "app-engine-python-extras",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "1.9.69",
    "name": "gcloud app Python Extensions (Extra Libraries)",
    "size": 29881362,
    "state": {
      "name": "Not Installed"
    }
  },
  {
    "current_version_string": "2.0.33",
    "id": "bq",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "2.0.33",
    "name": "BigQuery Command Line Tool",
    "size": 562687,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "",
    "id": "bigtable",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "Cloud Bigtable Emulator",
    "size": 3932939,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "2018.04.20",
    "id": "core",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "2018.04.20",
    "name": "Cloud SDK Core Libraries",
    "size": 8179458,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "4.30",
    "id": "gsutil",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "4.30",
    "name": "Cloud Storage Command Line Tool",
    "size": 3551781,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "2017.09.15",
    "id": "beta",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "2017.09.15",
    "name": "gcloud Beta Commands",
    "size": 688,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "1.9.63",
    "id": "app-engine-java",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "1.9.63",
    "name": "gcloud app Java Extensions",
    "size": 124632213,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": " ",
    "id": "app-engine-php",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": " ",
    "name": "gcloud app PHP Extensions",
    "size": 22985548,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "1.9.69",
    "id": "app-engine-python",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "1.9.69",
    "name": "gcloud app Python Extensions",
    "size": 6429916,
    "state": {
      "name": "Installed"
    }
  },
  {
    "current_version_string": "",
    "id": "kubectl",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "",
    "name": "kubectl",
    "size": 12789481,
    "state": {
      "name": "Installed"
    }
  }
]
```

**Comment by elharo** [comment]
May be a flaky test. It just passed for me.

**Comment by igorbernstein2** [comment]
That's odd, the test should be deterministic. If it's flaky, then it means that there might be an issue in our emulator. 

I'm having a hard time finding commit `51eba4e14c39df7dc97778ca7af36774ebbaf6cf`. Can you see if you can reproduce the issue against the current HEAD of master (`b559d674b14169487b34c68bf10160af8b1887b7`)

**Comment by igorbernstein2** [comment]
Ok, I found the underlying issue. It's a bug in the emulator that I'll try to get to this week.
