### ISSUE TITLE
Issue upgrading grpc logger

### ISSUE THREAD

**Issue by papudesi** [GoogleCloudPlatform/google-cloud-java#3219]
Upgrading our dependencies from grpc-core-1.7 to grpc-core-1.11.0, and grpc-netty-1.7.0 to grpc-netty-shaded-1.110, we get this exception:
```
Caused by: java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.ServiceProviders.load(ServiceProviders.java:42)
	at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:37)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:36)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:183)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:155)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:147)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:151)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:116)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:127)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:64)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:58)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:506)
	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:134)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:108)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:493)
	at com.google.cloud.logging.LoggingHandler.getLogging(LoggingHandler.java:360)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:195)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:151)
	at com.google.cloud.logging.LoggingHandler.<init>(LoggingHandler.java:120)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:563)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:506)
	at org.apache.juli.ClassLoaderLogManager$2.run(ClassLoaderLogManager.java:403)
	at org.apache.juli.ClassLoaderLogManager$2.run(ClassLoaderLogManager.java:399)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.juli.ClassLoaderLogManager.getClassLoaderInfo(ClassLoaderLogManager.java:399)
	at org.apache.juli.ClassLoaderLogManager.getLogger(ClassLoaderLogManager.java:230)
	at java.util.logging.LogManager.demandLogger(LogManager.java:551)
	at java.util.logging.Logger.demandLogger(Logger.java:455)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:67)
	at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:187)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:216)
	at org.apache.catalina.core.ContainerBase.getLogger(ContainerBase.java:360)
```
netty-shaded appears to have a `io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.`

**Comment by papudesi** [comment]
looks like spanner is the only offender: https://github.com/GoogleCloudPlatform/google-cloud-java/search?utf8=%E2%9C%93&q=%22import+io.grpc.netty.shaded.%22&type=

**Comment by papudesi** [comment]
however, using `grpc-netty` fixed my issue with gcloud logging. 🤷‍♂️

**Comment by pongad** [comment]
@papudesi Which version of logging did you see this problem on? Newer logging versions use grpc-netty-shaded so I'm a little confused how changing dependencies of grpc-netty could affect its behavior.

**Comment by pongad** [comment]
@papudesi I assume you're seeing this on the Tomcat runtime? For my own sanity, I checked `google-cloud-logging` locally and, by itself, it seems to work OK. If this occurs only on Tomcat, I think we should loop in Tomcat folks and figure out how to version sustainable :/

**Comment by pongad** [comment]
@papudesi The Tomcat runtime has never been stabilized and now deprecated, which explains why their dependencies are so far out of date. Is it possible for you to migrate to [Jetty](https://github.com/GoogleCloudPlatform/jetty-runtime)?
