### ISSUE TITLE
java.net.UnknownHostException: accounts.google.com

### ISSUE THREAD

**Issue by gaurav-m** [GoogleCloudPlatform/google-cloud-java#3233]
Hi 

I am trying to setup a server for a firebase based project.
When I run the sever(spring boot based sever) on my machine. I get the following issue

```
com.google.api.client.http.HttpRequest execute
WARNING: exception thrown while executing request
java.net.UnknownHostException: accounts.google.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:378)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:160)
	at com.google.firebase.FirebaseApp$TokenRefresher$1.call(FirebaseApp.java:548)
	at com.google.firebase.FirebaseApp$TokenRefresher$1.call(FirebaseApp.java:544)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Same thing happens with my firebase project url. As following
`java.net.UnknownHostException: xxxxxx-xxxxx.firebaseio.com: nodename nor servname provided, or not known`

Notes
1. If I start another terminal windows with 'ping accounts.google.com' and 'ping xxxxxx-xxxxx.firebaseio.com' and leave them running, I constantly receive ping packets. AND during this period the project(the spring based server) also runs fine!
2. This happens only on my wifi-router, doesnt happen, on my mobile hotspot, or on my server machine.
3. This is happening with my entire team.

Please note that I am not looking for complete solution here. Any help at any level is deeply appreciated. This has become a development nightmare for me and my team.

TIA

**Comment by pongad** [comment]
I think this issue is for https://github.com/firebase/firebase-admin-java, not this repo. @schmidt-sebastian can you confirm?

**Comment by gaurav-m** [comment]
@schmidt-sebastian @pongad Thanks for quick revert.
Will do that.
Btw there was something wrong with my router. Got fixed when I changed it.
I never found the root cause though.

**Comment by CH3T** [comment]
> @schmidt-sebastian @pongad Thanks for quick revert.
> Btw there was something wrong with my router. Got fixed when I changed it.
> I never found the root cause though.
@gaurav-m I am seeing this similar issue, do you mean a wireless router?

**Comment by karthikakn123** [comment]
Is this issue resolved

**Comment by schmidt-sebastian** [comment]
@karthikakn123 If you are still seeing this issue, please let us your dependencies and versions. Thanks!

**Comment by karthikakn123** [comment]
Import statements
------------------
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
dependencies 
-------------
json-path-4.1.2-dist
rest-assured-4.1.2-dist

**Comment by Bashirkhalil** [comment]
this issue is from your Server not fcm Server
