### ISSUE TITLE
Stackdriver Trace: com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.

### ISSUE THREAD

**Issue by songy23** [GoogleCloudPlatform/google-cloud-java#3250]
Hi there,

One of our customers got a exception when exporting via the v2 `TraceServiceClient`:

```java
[server] 2018-05-08 14:27:14,169 [ExportComponent.ServiceExporterThread-0] WARN  io.opencensus.trace.export.ExportComponent  - Exception thrown by the service export io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter
[server] com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
[server] at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45)
[server] at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
[server] at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
[server] at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
[server] at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
[server] at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
[server] at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
[server] at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1025)
[server] at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
[server] at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
[server] at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492)
[server] at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
[server] at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
[server] at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
[server] at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
[server] at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
[server] at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
[server] at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
[server] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
[server] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
[server] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
[server] at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[server] at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[server] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[server] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[server] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[server] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[server] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[server] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[server] at java.lang.Thread.run(Thread.java:745)
[server] Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
[server] at io.grpc.Status.asRuntimeException(Status.java:526)
[server] ... 19 more
```

He tried with version `0.42.0-alpha` and `0.34.0-beta`, but got this exception in both cases. He could also see this in Stackdriver trace view in the Google Cloud Console:
![image](https://user-images.githubusercontent.com/187029/39799419-70c7bfd4-5364-11e8-9a38-e18399ddf58d.png)

Any idea how this happened?

Original issue: https://github.com/census-instrumentation/opencensus-java/issues/1184

**Comment by pongad** [comment]
@songy23 I think we need more details here. What were you trying to do when this happens? The stack trace suggests that the server creates a failure that is propagated here by an exception. I don't think this is a client lib issue.

**Comment by songy23** [comment]
At first we suspect this is due to a dependency conflict. We used cloud client version `0.34.0-beta` in our library, while our user used client version `0.42.0-alpha`. However this issue persist even if the user updated his binary to use a consistent version for client.

@johanhaleby could you share more details about the the trace you want to send?

**Comment by johanhaleby** [comment]
Yes it's very simple. I just do this:

```java
StackdriverTraceExporter.createAndRegister(StackdriverTraceConfiguration.builder().setProjectId("projectId").build());

Span rootSpan = Tracing.getTracer().spanBuilder("Something").setSampler(Samplers.alwaysSample()).startSpan();
// Some code

rootSpan.end();
```

**Comment by songy23** [comment]
Closing - this particular error is due to authentication (bad project id format).
