### ISSUE TITLE
Exception in thread "grpc-default-executor-1" java.lang.IllegalArgumentException : Jetty ALPN/NPN has not been properly configured.         at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSsl Contexts.java:153)

### ISSUE THREAD

**Issue by mandeep1443** [GoogleCloudPlatform/google-cloud-java#3277]
May 16, 2018 11:43:39 AM com.example.flexible.speak.TranscribeSocket onWebSocket
Text
INFO: Got sampleRate: 48000
May 16, 2018 11:43:39 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@117866a] Created with target speech.googleapis.com:443

Exception in thread "grpc-default-executor-1" java.lang.IllegalArgumentException
: Jetty ALPN/NPN has not been properly configured.
        at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSsl
Contexts.java:153)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:130)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:119)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:90)
        at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiator(NettyChann
elBuilder.java:265)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTran
sport(NettyChannelBuilder.java:324)
        at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTra
nsport(CallCredentialsApplyingTransportFactory.java:62)
        at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:215
)
        at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java
:192)
        at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl
.java:651)
        at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl
.java:592)
        at io.grpc.DummyLoadBalancerFactory$DummyLoadBalancer$1.get(DummyLoadBal
ancerFactory.java:135)
        at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.
java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mandeep1443** [comment]
Dear All,

I have been struggling to solve this issue for past few days .Please see the logs in my previous comment.

I have downloaded code from : https://github.com/googlecodelabs/speaking-with-a-webpage/tree/master/04-speech

Steps followed -
1> Build project with command : mvn clean jetty:run
2>After server successfully started accessing the application using  : https://localhost:8443/
3>After recording speech from the UI page getting exception as below in console -

May 16, 2018 11:43:39 AM com.example.flexible.speak.TranscribeSocket onWebSocket
Text
INFO: Got sampleRate: 48000
May 16, 2018 11:43:39 AM io.grpc.internal.ManagedChannelImpl 
INFO: [ManagedChannelImpl@117866a] Created with target speech.googleapis.com:443

Exception in thread "grpc-default-executor-1" java.lang.IllegalArgumentException
: Jetty ALPN/NPN has not been properly configured.
at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSsl
Contexts.java:153)
at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:130)
at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:119)
at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:90)
at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiator(NettyChann
elBuilder.java:265)
at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTran
sport(NettyChannelBuilder.java:324)
at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTra
nsport(CallCredentialsApplyingTransportFactory.java:62)
at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:215
)
at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java
:192)
at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl
.java:651)
at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl
.java:592)
at io.grpc.DummyLoadBalancerFactory$DummyLoadBalancer$1.get(DummyLoadBal
ancerFactory.java:135)
at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.
java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624)
at java.lang.Thread.run(Thread.java:748)

Requesting someone to please help me to solve this problem

**Comment by garrettjonesgoogle** [comment]
Have you seen https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/TROUBLESHOOTING.md#alpn-is-not-configured-properly yet?

**Comment by garrettjonesgoogle** [comment]
Great to hear! It looks like we should update the troubleshooting guide to point people to the compat checker.

**Comment by garrettjonesgoogle** [comment]
Filed https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3284
