### ISSUE TITLE
Compute integration tests are failing

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#3312]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-java/6716?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.cloud.compute.deprecated.it.ITComputeTest
Tests run: 58, Failures: 0, Errors: 2, Skipped: 4, Time elapsed: 679.408 sec <<< FAILURE! - in com.google.cloud.compute.deprecated.it.ITComputeTest
testAggregatedListDiskTypes(com.google.cloud.compute.deprecated.it.ITComputeTest)  Time elapsed: 0.184 sec  <<< ERROR!
java.lang.IllegalArgumentException: https://www.googleapis.com/compute/v1/projects/gcloud-devel/regions/us-central1/diskTypes/local-ssd is not a valid disk type URL
```

**Comment by andreamlin** [comment]
@garrettjonesgoogle 
Can we `@Ignore` the 2 failing tests?

**Comment by andreamlin** [comment]
The two failing tests' errors:
```
testAggregatedListDiskTypes(com.google.cloud.compute.deprecated.it.ITComputeTest)  Time elapsed: 0.155 sec  <<< ERROR!
java.lang.IllegalArgumentException: https://www.googleapis.com/compute/v1/projects/gcloud-devel/regions/us-central1/diskTypes/local-ssd is not a valid disk type URL
	at com.google.cloud.compute.deprecated.DiskTypeId.fromUrl(DiskTypeId.java:149)
	at com.google.cloud.compute.deprecated.DiskType.fromPb(DiskType.java:234)
	at com.google.cloud.compute.deprecated.ComputeImpl$5.apply(ComputeImpl.java:542)
	at com.google.cloud.compute.deprecated.ComputeImpl$5.apply(ComputeImpl.java:539)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.cloud.compute.deprecated.it.ITComputeTest.testAggregatedListDiskTypes(ITComputeTest.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

testAggregatedListDiskTypesWithFilter(com.google.cloud.compute.deprecated.it.ITComputeTest)  Time elapsed: 0.164 sec  <<< ERROR!
java.lang.IllegalArgumentException: https://www.googleapis.com/compute/v1/projects/gcloud-devel/regions/us-central1/diskTypes/pd-ssd is not a valid disk type URL
	at com.google.cloud.compute.deprecated.DiskTypeId.fromUrl(DiskTypeId.java:149)
	at com.google.cloud.compute.deprecated.DiskType.fromPb(DiskType.java:234)
	at com.google.cloud.compute.deprecated.ComputeImpl$5.apply(ComputeImpl.java:542)
	at com.google.cloud.compute.deprecated.ComputeImpl$5.apply(ComputeImpl.java:539)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.cloud.compute.deprecated.it.ITComputeTest.testAggregatedListDiskTypesWithFilter(ITComputeTest.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Those two tests fail because diskTypes.aggregateList returns diskTypeIds in the form 
```
projects/{project}/regions/{region}/diskTypes/{diskType}
```
instead of the expected
```
projects/{project}/zones/{zone}/diskTypes/{diskType}
```

**Comment by andreamlin** [comment]
The CI build for the linked PR passed: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-java/7353#artifacts/containers/0 passed; although it didn't run ITComputeTest...
