### ISSUE TITLE
Getting `com.google.common.util.concurrent.MoreExecutors.directExecutor` for using BigQuery

### ISSUE THREAD

**Issue by kansuke231** [GoogleCloudPlatform/google-cloud-java#3488]
Hi all.

I am getting `java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor`for a line:

```java
TableDataWriteChannel writer = bigQuery.writer(writeChannelConfiguration);
````

Here is the part of stacktrace:
```
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:77)
	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:73)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:73)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.bigquery.TableDataWriteChannel.open(TableDataWriteChannel.java:76)
	at com.google.cloud.bigquery.TableDataWriteChannel.<init>(TableDataWriteChannel.java:41)
	at com.google.cloud.bigquery.BigQueryImpl.writer(BigQueryImpl.java:729)
	at com.google.cloud.bigquery.BigQueryImpl.writer(BigQueryImpl.java:720)
```

I have investigated this error and it seems that this is usually caused by the old version of guava leaking into the dependency. However, it does not seem to be the case here. Below are snippets of `pom.xml` and the result of `mvn dependency:tree`:

pom.xml -->
```

 <dependencyManagement>
   <dependencies>
     <dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>aws-java-sdk-bom</artifactId>
       <version>1.11.320</version>
       <type>pom</type>
       <scope>import</scope>
     </dependency>
       <dependency>
           <groupId>com.google.guava</groupId>
           <artifactId>guava</artifactId>
           <version>25.0-jre</version>
       </dependency>
   </dependencies>
 </dependencyManagement>
 <dependencies>
     <dependency>
       <groupId>org.apache.httpcomponents</groupId>
       <artifactId>httpclient</artifactId>
       <version>4.5.4</version>
     </dependency>
   <dependency>
       <groupId>org.apache.spark</groupId>
       <artifactId>spark-streaming_2.11</artifactId>
       <version>2.2.0</version>
   </dependency>
   
   <dependency>
       <groupId>org.json</groupId>
       <artifactId>json</artifactId>
       <version>20160810</version>
   </dependency>
   <dependency>
     <groupId>com.amazonaws</groupId>
     <artifactId>aws-java-sdk-s3</artifactId>
   </dependency>
   <dependency>
     <groupId>com.amazonaws</groupId>
     <artifactId>aws-java-sdk-lambda</artifactId>
   </dependency>
   <dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>aws-java-sdk-kms</artifactId>
   </dependency>
   <dependency>
     <groupId>org.apache.commons</groupId>
     <artifactId>commons-lang3</artifactId>
     <version>3.5</version>
   </dependency>
   <dependency>
     <groupId>junit</groupId>
     <artifactId>junit</artifactId>
     <version>3.8.1</version>
     <scope>test</scope>
   </dependency>
   <dependency>
       <groupId>org.apache.spark</groupId>
       <artifactId>spark-core_2.11</artifactId>
       <version>2.2.0</version>
       <scope>provided</scope>
       <exclusions>
           <exclusion> <!-- exclude an old version of Guava -->
               <groupId>com.google.guava</groupId>
               <artifactId>guava-jdk5</artifactId>
           </exclusion>
           <exclusion> <!-- exclude an old version of Guava -->
               <groupId>com.google.guava</groupId>
               <artifactId>guava</artifactId>
           </exclusion>
       </exclusions>
   </dependency>
   <dependency>
       <groupId>org.scala-lang</groupId>
       <artifactId>scala-library</artifactId>
       <version>2.11.8</version>
       <scope>provided</scope>
   </dependency>
   <dependency>
       <groupId>org.apache.spark</groupId>
       <artifactId>spark-sql_2.11</artifactId>
       <version>2.2.0</version>
       <scope>provided</scope>
   </dependency>
   <dependency>
       <groupId>com.fasterxml.jackson.dataformat</groupId>
       <artifactId>jackson-dataformat-csv</artifactId>
       <version>2.6.5</version>
   </dependency>
   <dependency>
       <groupId>com.hubspot.jinjava</groupId>
       <artifactId>jinjava</artifactId>
       <version>2.3.4</version>
       <exclusions>
           <exclusion> <!-- exclude an old version of Guava -->
               <groupId>com.google.guava</groupId>
               <artifactId>guava-jdk5</artifactId>
           </exclusion>
           <exclusion> <!-- exclude an old version of Guava -->
               <groupId>com.google.guava</groupId>
               <artifactId>guava</artifactId>
           </exclusion>
       </exclusions>
   </dependency>
   <dependency>
       <groupId>com.fasterxml.jackson.dataformat</groupId>
       <artifactId>jackson-dataformat-yaml</artifactId>
       <version>2.6.5</version>
   </dependency>
   <dependency>
       <groupId>com.fasterxml.jackson.core</groupId>
       <artifactId>jackson-databind</artifactId>
       <version>2.6.5</version>
   </dependency>
   

     <dependency>
         <groupId>com.google.guava</groupId>
         <artifactId>guava</artifactId>
         <version>25.0-jre</version>
     </dependency>
     <dependency>
         <groupId>com.google.cloud</groupId>
         <artifactId>google-cloud-bigquery</artifactId>
         <version>1.36.0</version>
     </dependency>
     
     <dependency>
         <groupId>com.google.apis</groupId>
         <artifactId>google-api-services-pubsub</artifactId>
         <version>v1-rev395-1.23.0</version>
     </dependency>
     <dependency>
         <groupId>com.google.cloud</groupId>
         <artifactId>google-cloud-storage</artifactId>
         <version>1.36.0</version>
     </dependency>
     <dependency>
         <groupId>com.google.api-client</groupId>
         <artifactId>google-api-client</artifactId>
         <version>1.23.0</version>
         <exclusions>
             <exclusion> <!-- exclude an old version of Guava -->
                 <groupId>com.google.guava</groupId>
                 <artifactId>guava-jdk5</artifactId>
             </exclusion>
             <exclusion> <!-- exclude an old version of Guava -->
                 <groupId>com.google.guava</groupId>
                 <artifactId>guava</artifactId>
             </exclusion>
         </exclusions>
     </dependency>
     <dependency>
         <groupId>com.google.cloud</groupId>
         <artifactId>google-cloud-pubsub</artifactId>
         <version>1.36.0</version>
     </dependency>
     <dependency>
         <groupId>com.google.api</groupId>
         <artifactId>gax</artifactId>
         <version>1.29.0</version>
         <exclusions>
             <exclusion> <!-- exclude an old version of Guava -->
                 <groupId>com.google.guava</groupId>
                 <artifactId>guava-jdk5</artifactId>
             </exclusion>
             <exclusion> <!-- exclude an old version of Guava -->
                 <groupId>com.google.guava</groupId>
                 <artifactId>guava</artifactId>
             </exclusion>
         </exclusions>
     </dependency>
     <dependency>
         <groupId>com.google.api</groupId>
         <artifactId>gax-grpc</artifactId>
         <version>1.29.0</version>
         <scope>test</scope>
         <exclusions>
             <exclusion> <!-- exclude an old version of Guava -->
                 <groupId>com.google.guava</groupId>
                 <artifactId>guava-jdk5</artifactId>
             </exclusion>
             <exclusion> <!-- exclude an old version of Guava -->
                 <groupId>com.google.guava</groupId>
                 <artifactId>guava</artifactId>
             </exclusion>
         </exclusions>
     </dependency>
    
     <dependency>
         <groupId>com.amazonaws</groupId>
         <artifactId>aws-java-sdk-redshift</artifactId>
     </dependency>
     <dependency>
         <groupId>com.amazon.redshift</groupId>
         <artifactId>redshift-jdbc42</artifactId>
         <version>1.2.1.1001</version>
     </dependency>
     <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>42.1.1</version>
     </dependency>
   <dependency>
       <groupId>postgresql</groupId>
       <artifactId>postgresql</artifactId>
       <version>9.1-901-1.jdbc4</version>
   </dependency>
   <dependency>
       <groupId>com.auth0</groupId>
       <artifactId>java-jwt</artifactId>
       <version>3.1.0</version>
   </dependency>
   <dependency>
       <groupId>com.jcraft</groupId>
       <artifactId>jsch</artifactId>
       <version>0.1.54</version>
   </dependency>
     <dependency>
         <groupId>com.microsoft.azure</groupId>
         <artifactId>adal4j</artifactId>
         <version>1.1.3</version>
     </dependency>
     <dependency>
         <groupId>com.crealytics</groupId>
         <artifactId>spark-excel_2.11</artifactId>
         <version>0.9.15</version>
     </dependency>
 </dependencies>
 <build>
   <plugins>
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-compiler-plugin</artifactId>
         <version>3.3</version>
         <configuration>
              <source>1.8</source>
              <target>1.8</target>
           </configuration>
       </plugin>
       <plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-shade-plugin</artifactId>
   <version>2.3</version>
   <executions>
     <execution>
       <phase>package</phase>
       <goals>
         <goal>shade</goal>
       </goals>
       <configuration>
         <transformers>
             <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
         </transformers>
         <filters>
           <filter>
             <artifact>*:*</artifact>
             <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
                <exclude>junit:junit</exclude>
                <exclude>org.apache.maven:lib:tests</exclude>
            </excludes>
           </filter>
        </filters>
       </configuration>
     </execution>
   </executions>
 </plugin>
   </plugins>
 </build>
</project>
```
`mvn dependency:tree` --> 
```
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.4:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.7:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- org.apache.spark:spark-streaming_2.11:jar:2.2.0:compile
[INFO] |  +- org.apache.spark:spark-tags_2.11:jar:2.2.0:compile
[INFO] |  \- org.spark-project.spark:unused:jar:1.0.0:compile
[INFO] +- org.json:json:jar:20160810:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.320:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.320:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.320:compile
[INFO] +- com.amazonaws:aws-java-sdk-lambda:jar:1.11.320:compile
[INFO] +- com.amazonaws:aws-java-sdk-kms:jar:1.11.320:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] +- junit:junit:jar:3.8.1:test
[INFO] +- org.apache.spark:spark-core_2.11:jar:2.2.0:provided
[INFO] |  +- org.apache.avro:avro:jar:1.7.7:provided
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.3:provided
[INFO] |  |  \- org.apache.commons:commons-compress:jar:1.4.1:provided
[INFO] |  |     \- org.tukaani:xz:jar:1.0:provided
[INFO] |  +- org.apache.avro:avro-mapred:jar:hadoop2:1.7.7:provided
[INFO] |  |  +- org.apache.avro:avro-ipc:jar:1.7.7:provided
[INFO] |  |  \- org.apache.avro:avro-ipc:jar:tests:1.7.7:provided
[INFO] |  +- com.twitter:chill_2.11:jar:0.8.0:provided
[INFO] |  |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:provided
[INFO] |  |     \- com.esotericsoftware:minlog:jar:1.3.0:provided
[INFO] |  +- com.twitter:chill-java:jar:0.8.0:provided
[INFO] |  +- org.apache.xbean:xbean-asm5-shaded:jar:4.4:provided
[INFO] |  +- org.apache.hadoop:hadoop-client:jar:2.6.5:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-common:jar:2.6.5:provided
[INFO] |  |  |  +- commons-cli:commons-cli:jar:1.2:provided
[INFO] |  |  |  +- xmlenc:xmlenc:jar:0.52:provided
[INFO] |  |  |  +- commons-httpclient:commons-httpclient:jar:3.1:provided
[INFO] |  |  |  +- commons-collections:commons-collections:jar:3.2.2:provided
[INFO] |  |  |  +- commons-lang:commons-lang:jar:2.6:provided
[INFO] |  |  |  +- commons-configuration:commons-configuration:jar:1.6:provided
[INFO] |  |  |  |  +- commons-digester:commons-digester:jar:1.8:provided
[INFO] |  |  |  |  \- commons-beanutils:commons-beanutils-core:jar:1.8.0:provided
[INFO] |  |  |  +- org.apache.hadoop:hadoop-auth:jar:2.6.5:provided
[INFO] |  |  |  |  \- org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15:provided
[INFO] |  |  |  |     +- org.apache.directory.server:apacheds-i18n:jar:2.0.0-M15:provided
[INFO] |  |  |  |     +- org.apache.directory.api:api-asn1-api:jar:1.0.0-M20:provided
[INFO] |  |  |  |     \- org.apache.directory.api:api-util:jar:1.0.0-M20:provided
[INFO] |  |  |  +- org.apache.curator:curator-client:jar:2.6.0:provided
[INFO] |  |  |  \- org.htrace:htrace-core:jar:3.0.4:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-hdfs:jar:2.6.5:provided
[INFO] |  |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |  |  \- xerces:xercesImpl:jar:2.9.1:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.6.5:provided
[INFO] |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.6.5:provided
[INFO] |  |  |  |  +- org.apache.hadoop:hadoop-yarn-client:jar:2.6.5:provided
[INFO] |  |  |  |  \- org.apache.hadoop:hadoop-yarn-server-common:jar:2.6.5:provided
[INFO] |  |  |  \- org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.6.5:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-yarn-api:jar:2.6.5:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.6.5:provided
[INFO] |  |  |  \- org.apache.hadoop:hadoop-yarn-common:jar:2.6.5:provided
[INFO] |  |  |     +- javax.xml.bind:jaxb-api:jar:2.2.2:provided
[INFO] |  |  |     +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:provided
[INFO] |  |  |     \- org.codehaus.jackson:jackson-xc:jar:1.9.13:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.6.5:provided
[INFO] |  |  \- org.apache.hadoop:hadoop-annotations:jar:2.6.5:provided
[INFO] |  +- org.apache.spark:spark-launcher_2.11:jar:2.2.0:provided
[INFO] |  +- org.apache.spark:spark-network-common_2.11:jar:2.2.0:provided
[INFO] |  |  \- org.fusesource.leveldbjni:leveldbjni-all:jar:1.8:provided
[INFO] |  +- org.apache.spark:spark-network-shuffle_2.11:jar:2.2.0:provided
[INFO] |  +- org.apache.spark:spark-unsafe_2.11:jar:2.2.0:provided
[INFO] |  +- net.java.dev.jets3t:jets3t:jar:0.9.3:provided
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  +- mx4j:mx4j:jar:3.0.2:provided
[INFO] |  |  +- javax.mail:mail:jar:1.4.7:compile
[INFO] |  |  \- com.jamesmurty.utils:java-xmlbuilder:jar:1.0:provided
[INFO] |  |     \- net.iharder:base64:jar:2.3.8:provided
[INFO] |  +- org.apache.curator:curator-recipes:jar:2.6.0:provided
[INFO] |  |  +- org.apache.curator:curator-framework:jar:2.6.0:provided
[INFO] |  |  \- org.apache.zookeeper:zookeeper:jar:3.4.6:provided
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.4.1:provided
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.16:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.16:provided
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.16:provided
[INFO] |  +- log4j:log4j:jar:1.2.17:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.16:provided
[INFO] |  +- com.ning:compress-lzf:jar:1.0.3:provided
[INFO] |  +- org.xerial.snappy:snappy-java:jar:1.1.2.6:provided
[INFO] |  +- net.jpountz.lz4:lz4:jar:1.3.0:provided
[INFO] |  +- org.roaringbitmap:RoaringBitmap:jar:0.5.11:provided
[INFO] |  +- commons-net:commons-net:jar:2.2:provided
[INFO] |  +- org.json4s:json4s-jackson_2.11:jar:3.2.11:provided
[INFO] |  |  \- org.json4s:json4s-core_2.11:jar:3.2.11:provided
[INFO] |  |     +- org.json4s:json4s-ast_2.11:jar:3.2.11:provided
[INFO] |  |     \- org.scala-lang:scalap:jar:2.11.0:provided
[INFO] |  |        \- org.scala-lang:scala-compiler:jar:2.11.0:provided
[INFO] |  |           \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.1:provided
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:2.22.2:provided
[INFO] |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:provided
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.4.0-b34:provided
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b34:provided
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34:provided
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:provided
[INFO] |  |  \- org.glassfish.hk2:hk2-locator:jar:2.4.0-b34:provided
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:2.22.2:provided
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:provided
[INFO] |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.2:provided
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:provided
[INFO] |  +- org.glassfish.jersey.core:jersey-server:jar:2.22.2:provided
[INFO] |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.22.2:provided
[INFO] |  |  \- javax.validation:validation-api:jar:1.1.0.Final:provided
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.2:provided
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.22.2:provided
[INFO] |  +- io.netty:netty-all:jar:4.0.43.Final:provided
[INFO] |  +- io.netty:netty:jar:3.9.9.Final:provided
[INFO] |  +- com.clearspring.analytics:stream:jar:2.7.0:provided
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:3.1.2:provided
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:provided
[INFO] |  +- io.dropwizard.metrics:metrics-json:jar:3.1.2:provided
[INFO] |  +- io.dropwizard.metrics:metrics-graphite:jar:3.1.2:provided
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-scala_2.11:jar:2.6.5:provided
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.11.7:provided
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.6.5:provided
[INFO] |  +- org.apache.ivy:ivy:jar:2.4.0:provided
[INFO] |  +- oro:oro:jar:2.0.8:provided
[INFO] |  +- net.razorvine:pyrolite:jar:4.13:provided
[INFO] |  +- net.sf.py4j:py4j:jar:0.10.4:provided
[INFO] |  \- org.apache.commons:commons-crypto:jar:1.0.0:provided
[INFO] +- org.scala-lang:scala-library:jar:2.11.8:provided
[INFO] +- org.apache.spark:spark-sql_2.11:jar:2.2.0:provided
[INFO] |  +- com.univocity:univocity-parsers:jar:2.2.1:provided
[INFO] |  +- org.apache.spark:spark-sketch_2.11:jar:2.2.0:provided
[INFO] |  +- org.apache.spark:spark-catalyst_2.11:jar:2.2.0:provided
[INFO] |  |  +- org.codehaus.janino:janino:jar:3.0.0:provided
[INFO] |  |  +- org.codehaus.janino:commons-compiler:jar:3.0.0:provided
[INFO] |  |  \- org.antlr:antlr4-runtime:jar:4.5.3:provided
[INFO] |  +- org.apache.parquet:parquet-column:jar:1.8.2:provided
[INFO] |  |  +- org.apache.parquet:parquet-common:jar:1.8.2:provided
[INFO] |  |  \- org.apache.parquet:parquet-encoding:jar:1.8.2:provided
[INFO] |  \- org.apache.parquet:parquet-hadoop:jar:1.8.2:provided
[INFO] |     +- org.apache.parquet:parquet-format:jar:2.3.1:provided
[INFO] |     \- org.apache.parquet:parquet-jackson:jar:1.8.2:provided
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-csv:jar:2.6.5:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.5:compile
[INFO] +- com.hubspot.jinjava:jinjava:jar:2.3.4:compile
[INFO] |  +- org.javassist:javassist:jar:3.18.2-GA:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.8.1:compile
[INFO] |  \- com.google.code.findbugs:annotations:jar:3.0.0:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.6.5:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.15:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.5:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] +- some_project_1:jar:1.0.2:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client-jetty:jar:1.22.0:compile
[INFO] |  |  +- com.google.oauth-client:google-oauth-client-java6:jar:1.22.0:compile
[INFO] |  |  \- org.mortbay.jetty:jetty:jar:6.1.26:compile
[INFO] |  |     \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:compile
[INFO] |  \- com.google.apis:google-api-services-sheets:jar:v4-rev18-1.22.0:compile
[INFO] +- com.google.guava:guava:jar:25.0-jre:compile
[INFO] |  +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] +- com.google.cloud:google-cloud-bigquery:jar:1.36.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.36.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.6.0:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core-http:jar:1.36.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client-appengine:jar:1.23.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client-jackson:jar:1.23.0:compile
[INFO] |  |  +- com.google.api:gax-httpjson:jar:0.46.0:compile
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.12.3:compile
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.12.3:compile
[INFO] |  +- com.google.auto.value:auto-value:jar:1.4:compile
[INFO] |  \- com.google.apis:google-api-services-bigquery:jar:v2-rev383-1.23.0:compile
[INFO] +- com.google.apis:google-api-services-pubsub:jar:v1-rev395-1.23.0:compile
[INFO] +- com.google.cloud:google-cloud-storage:jar:1.36.0:compile
[INFO] |  \- com.google.apis:google-api-services-storage:jar:v1-rev131-1.23.0:compile
[INFO] +- com.google.api-client:google-api-client:jar:1.23.0:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.23.0:compile
[INFO] |  \- com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile
[INFO] +- com.google.cloud:google-cloud-pubsub:jar:1.36.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.36.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.6.0:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.13.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:1.18.0:compile
[INFO] |  +- com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:1.18.0:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.13.1:compile
[INFO] |  |  \- io.grpc:grpc-core:jar:1.13.1:compile (version selected from constraint [1.13.1,1.13.1])
[INFO] |  |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.12.3:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.13.1:compile
[INFO] |  \- io.grpc:grpc-auth:jar:1.13.1:compile
[INFO] +- com.google.api:gax:jar:1.29.0:compile
[INFO] |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.9.1:compile
[INFO] |  \- com.google.api:api-common:jar:1.6.0:compile
[INFO] +- com.google.api:gax-grpc:jar:1.29.0:test
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.10.1:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.10.1:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:0.9.1:compile
[INFO] |  \- com.google.api.grpc:proto-google-common-protos:jar:1.0.0:compile
[INFO] +- some_project_2:jar:1.0.7:compile
[INFO] |  +- some_project_3:jar:1.0.7:compile
[INFO] |  |  \- com.google.apis:google-api-services-sqladmin:jar:v1beta4-rev25-1.22.0:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.1:compile
[INFO] |  \- mysql:mysql-connector-java:jar:5.1.38:compile
[INFO] +- some_project_4:jar:1.0.7:compile
[INFO] +- com.amazonaws:aws-java-sdk-redshift:jar:1.11.320:compile
[INFO] +- com.amazon.redshift:redshift-jdbc42:jar:1.2.1.1001:compile
[INFO] +- org.postgresql:postgresql:jar:42.1.1:compile
[INFO] +- postgresql:postgresql:jar:9.1-901-1.jdbc4:compile
[INFO] +- com.auth0:java-jwt:jar:3.1.0:compile
[INFO] |  \- org.bouncycastle:bcprov-jdk15on:jar:1.55:compile
[INFO] +- com.jcraft:jsch:jar:0.1.54:compile
[INFO] +- com.microsoft.azure:adal4j:jar:1.1.3:compile
[INFO] |  +- com.nimbusds:oauth2-oidc-sdk:jar:4.5:compile
[INFO] |  |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  |  +- net.minidev:json-smart:jar:1.1.1:compile
[INFO] |  |  +- com.nimbusds:lang-tag:jar:1.4:compile
[INFO] |  |  \- com.nimbusds:nimbus-jose-jwt:jar:3.1.2:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] \- com.crealytics:spark-excel_2.11:jar:0.9.15:compile
[INFO]    +- org.apache.poi:poi-ooxml:jar:3.17:compile
[INFO]    |  +- org.apache.poi:poi:jar:3.17:compile
[INFO]    |  |  \- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO]    |  +- org.apache.poi:poi-ooxml-schemas:jar:3.17:compile
[INFO]    |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO]    |  |     \- stax:stax-api:jar:1.0.1:compile
[INFO]    |  \- com.github.virtuald:curvesapi:jar:1.04:compile
[INFO]    +- com.norbitltd:spoiwo_2.11:jar:1.2.0:compile
[INFO]    |  +- org.scala-lang.modules:scala-xml_2.11:jar:1.0.6:compile
[INFO]    |  \- org.joda:joda-convert:jar:1.8.1:compile
[INFO]    \- com.monitorjbl:xlsx-streamer:jar:1.2.1:compile
[INFO]       +- com.rackspace.apache:xerces2-xsd11:jar:2.11.1:compile
[INFO]       |  +- com.rackspace.eclipse.webtools.sourceediting:org.eclipse.wst.xml.xpath2.processor:jar:2.1.100:compile
[INFO]       |  |  +- edu.princeton.cup:java-cup:jar:10k:compile
[INFO]       |  |  \- com.ibm.icu:icu4j:jar:4.6:compile
[INFO]       |  \- xml-resolver:xml-resolver:jar:1.2:compile
[INFO]       \- xml-apis:xml-apis:jar:1.4.01:compile
```

**Comment by hzyi-google** [comment]
Hi @kansuke231 ,

I used exactly the same pom you provided and in my main function I did:

```java
System.out.println(MoreExecutors.directExecutor());
```
and the build was successful. Could you please double check on your side?

**Comment by kansuke231** [comment]
Hi @hzyi-google. 

Thanks for the response. This was caused in runtime so the compilation was successful. I put the print line as you did in my code too. The IDE did not complain, it compiled well but I got the same error message for that print line. I suspect some sort of reflection is used in the code, so the compilation cannot catch the exception.

**Comment by hzyi-google** [comment]
Sorry I didn't make myself clear - I was able to build AND run successfully. I am most probably not familiar with the IDE you are using, but could you try removing any possible cached packages and do a clean build?
