### ISSUE TITLE
Inconsistent Connection with Firestore when using Java Google App Engine

### ISSUE THREAD

**Issue by jonnjonny** [GoogleCloudPlatform/google-cloud-java#3556]
Hello,

I am having issues with connecting to firestore in a consistent manner. Accessing firestore sometimes is successful but also fails with the following error.

> java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500) at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479) at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76) at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) at com.friendzonellc.match.Matching.match(Matching.java:136) at com.friendzonellc.match.Matching.doGet(Matching.java:104) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) at 
...
io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:69) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) at com.google.api.gax.grpc.GrpcExceptionServerStreamingCallable$ExceptionResponseObserver.onErrorImpl(GrpcExceptionServerStreamingCallable.java:105) at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86) at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:127) at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391) at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475) at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)

I am currently authenticating under a static initializer within a class extending the HttpServlet class. 

```
static {
try {
      serviceAccount = new FileInputStream("WEB-INF/admin-sdk-key.json");
      options  = new FirebaseOptions.Builder()
                                    .setCredentials(GoogleCredentials.fromStream(serviceAccount))
                                    .setDatabaseUrl("${OUR_DATABASE_URL}")
                                    .build();
      FirebaseApp.initializeApp(options);

      db = FirestoreClient.getFirestore();
    }
catch (Exception e) {
      StringWriter sw = new StringWriter();
      PrintWriter pw = new PrintWriter(sw);
      e.printStackTrace(pw);
      log.info(sw.toString());
    }
}
```
The class accepts a get request which proceeds to call another function that requires access to the Firestore.

This is the code that I am using to obtain a Document Snapshot. 

```
DocumentReference userRef = userCollection.document(userid);
    ApiFuture<DocumentSnapshot> userSnap = userRef.get();
    DocumentSnapshot userDocumentSnap = userSnap.get();
    Map<String,Object> userDocument = userDocumentSnap.getData();
```

Whenever this fails, it raises an error when calling get on the ApiFuture<DocumentSnapshot> object. 

The following dependencies I am using at the moment in my pom.xml is the following:

```
<dependency>
<groupId>com.google.appengine</groupId>
<artifactId>appengine-api-1.0-sdk</artifactId>
<version>1.9.64</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud</artifactId>
      <version>0.47.0-alpha</version>
    </dependency>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-admin</artifactId>
      <version>6.3.0</version>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <type>jar</type>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jstl</groupId>
      <artifactId>jstl</artifactId>
      <version>1.2</version>
    </dependency>
```

Any suggestions would be much appreciated. Thank you!

**Comment by jonnjonny** [comment]
I just fixed it by using the google-cloud-firestore artifact.

**Comment by jonnjonny** [comment]
Same error is occurring even though I updated to 0.56.0 beta google-cloud-firestore
