### ISSUE TITLE
Java Logging 'com.google.cloud.logging.LoggingHandlerTest' fails

### ISSUE THREAD

**Issue by suhasm21** [GoogleCloudPlatform/google-cloud-java#3615]
URL: https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-logging

Running com.google.cloud.logging.LoggingHandlerTest
Tests run: 15, Failures: 11, Errors: 0, Skipped: 0, Time elapsed: 0.273 sec <<< FAILURE! - in com.google.cloud.logging.LoggingHandlerTest

Please refer attached logs for further details.
[JavaLoggingTestFail.docx](https://github.com/GoogleCloudPlatform/google-cloud-java/files/2330431/JavaLoggingTestFail.docx)

**Comment by hzyi-google** [comment]
Below is the logs about the fails tests extracted from JavaLoggingTestFail.docx:
```java
com.google.cloud.logging.LoggingHandlerTest
testClose(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.116 sec  <<< FAILURE!
java.lang.AssertionError: 

  Unexpected method call Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=gce_instance, labels={instance_id=7441014457265456783, project_id=project, zone=us-west2-a}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}):
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.close(): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.testClose(LoggingHandlerTest.java:526)

testClose(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.117 sec  <<< FAILURE!
java.lang.AssertionError: 

  Expectation failure on verify:
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.close(): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.after(LoggingHandlerTest.java:209)

testPublishLevels(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: 

  Unexpected method call Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=gce_instance, labels={instance_id=7441014457265456783, project_id=project, zone=us-west2-a}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}):
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINER, levelValue=400}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINE, levelValue=500}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=INFO, insertId=null, httpRequest=null, labels={levelName=CONFIG, levelValue=700}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=INFO, insertId=null, httpRequest=null, labels={}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=WARNING, insertId=null, httpRequest=null, labels={levelName=WARNING, levelValue=900}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=ERROR, insertId=null, httpRequest=null, labels={levelName=SEVERE, levelValue=1000}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=DEBUG, levelValue=250}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=NOTICE, insertId=null, httpRequest=null, labels={levelName=NOTICE, levelValue=850}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=ERROR, insertId=null, httpRequest=null, labels={levelName=ERROR, levelValue=950}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=CRITICAL, insertId=null, httpRequest=null, labels={levelName=CRITICAL, levelValue=1050}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=ALERT, insertId=null, httpRequest=null, labels={levelName=ALERT, levelValue=1100}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=EMERGENCY, insertId=null, httpRequest=null, labels={levelName=EMERGENCY, levelValue=1150}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.testPublishLevels(LoggingHandlerTest.java:257)

testPublishLevels(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.027 sec  <<< FAILURE!
java.lang.AssertionError: 

  Expectation failure on verify:
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINER, levelValue=400}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINE, levelValue=500}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=INFO, insertId=null, httpRequest=null, labels={levelName=CONFIG, levelValue=700}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=INFO, insertId=null, httpRequest=null, labels={}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=WARNING, insertId=null, httpRequest=null, labels={levelName=WARNING, levelValue=900}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=ERROR, insertId=null, httpRequest=null, labels={levelName=SEVERE, levelValue=1000}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=DEBUG, levelValue=250}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=NOTICE, insertId=null, httpRequest=null, labels={levelName=NOTICE, levelValue=850}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=ERROR, insertId=null, httpRequest=null, labels={levelName=ERROR, levelValue=950}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=CRITICAL, insertId=null, httpRequest=null, labels={levelName=CRITICAL, levelValue=1050}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=ALERT, insertId=null, httpRequest=null, labels={levelName=ALERT, levelValue=1100}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=EMERGENCY, insertId=null, httpRequest=null, labels={levelName=EMERGENCY, levelValue=1150}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.after(LoggingHandlerTest.java:209)

testReportFlushError(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: 

  Unexpected method call Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=gce_instance, labels={instance_id=7441014457265456783, project_id=project, zone=us-west2-a}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}):
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.flush(): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.testReportFlushError(LoggingHandlerTest.java:395)

testReportFlushError(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: 

  Expectation failure on verify:
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
    Logging.flush(): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.after(LoggingHandlerTest.java:209)

testReportWriteError(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: 

  Unexpected method call Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=gce_instance, labels={instance_id=7441014457265456783, project_id=project, zone=us-west2-a}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}):
        at com.google.cloud.logging.LoggingHandlerTest.testReportWriteError(LoggingHandlerTest.java:369)

testSyncWrite(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: 

  Unexpected method call Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=gce_instance, labels={instance_id=7441014457265456783, project_id=project, zone=us-west2-a}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}):
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.testSyncWrite(LoggingHandlerTest.java:482)

testSyncWrite(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: 

  Expectation failure on verify:
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.after(LoggingHandlerTest.java:209)

testAddHandler(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: 

  Unexpected method call Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=gce_instance, labels={instance_id=7441014457265456783, project_id=project, zone=us-west2-a}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}):
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.testAddHandler(LoggingHandlerTest.java:507)

testAddHandler(com.google.cloud.logging.LoggingHandlerTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.AssertionError: 

  Expectation failure on verify:
    Logging.write([LogEntry{logName=null, resource=null, timestamp=123456789, receiveTimestamp=null, severity=DEBUG, insertId=null, httpRequest=null, labels={levelName=FINEST, levelValue=300}, operation=null, trace=null, spanId=null, sourceLocation=null, payload=StringPayload{type=STRING, data=message}}], WriteOption{name=LOG_NAME, value=java.log}, WriteOption{name=RESOURCE, value=MonitoredResource{type=global, labels={project_id=project}}}, WriteOption{name=LABELS, value={levelName=INFO, levelValue=800}}): expected: 1, actual: 0
        at com.google.cloud.logging.LoggingHandlerTest.after(LoggingHandlerTest.java:209)
```

**Comment by hzyi-google** [comment]
@suhasm21 which version of logging are you using? I am running on master and can't see any of the failures you mentioned.

**Comment by suhasm21** [comment]
It is 1.40.1-SNAPSHOT at commit bed08ffd27d1d232f229df20bc9f01da322131a8

However I updated the repo, it is now 1.41.1-SNAPSHOT at commit 08a5e469890da4ca2fbba456abbc8c39284dd821

and I still see the same error when I run the Logging test.

**Comment by hzyi-google** [comment]
This issue would happen when running on GCE. GCE would override the [`DEFAULT_RESOURCE`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/08a5e469890da4ca2fbba456abbc8c39284dd821/google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingHandlerTest.java#L49) and that's causing the tests to fail. There's nothing wrong with the logging library but we should fix the tests.
