### ISSUE TITLE
DefaultCredentialsProvider doesn't respect the CLOUDSDK_CONFIG environment variable

### ISSUE THREAD

**Issue by dimo414** [GoogleCloudPlatform/google-cloud-java#680]
`ServiceOptions.googleCloudProjectId()` first checks to see if `CLOUDSDK_CONFIG` has been set, and uses that in place of `~/.config/gcloud` if it has. However `DefaultCredentialsProvider.getWellKnownCredentialsFile()` does not, instead only looking in the default directory.

**Comment by mziccard** [comment]
Hi @dimo414 thanks for the feedback. 

Let me be sure I understood correctly. Does this problem cause our `ApplicationDefaultAuthCredentials.credentials()` not to find credentials when CLOUDSDK_CONFIG is set and points to a different location than the default one? (I can't check this now as I don't have access to a laptop). 

If this is the case we should probably report this issue at https://github.com/google/google-auth-library-java (where `DefaultCredentialsProvider` belongs) while trying to provide a workaround until it gets fixed.

**Comment by dimo414** [comment]
That's correct, here's a sample (in a `gcloud` logged-in shell):

```
$ CLOUDSDK_CONFIG=/tmp/.config/gcloud \
  java -cp GCloudDemo.jar com.google.gcloud.examples.storage.StorageExample list                    
Exception in thread "main" java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.googl.com/accounts/docs/application-default-credentials for more information.
        at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:74)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:54)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:36)
        at com.google.gcloud.AuthCredentials$ApplicationDefaultAuthCredentials.<init>(AuthCredentials.java:232)
        at com.google.gcloud.AuthCredentials.createApplicationDefaults(AuthCredentials.java:265)
        at com.google.gcloud.examples.storage.StorageExample.main(StorageExample.java:548)

```

**Comment by ajkannan** [comment]
Hi @dimo414, thanks for reporting this issue.  I agree with @mziccard's analysis, and I’ve created an issue in that library (issue 58 linked above).  As a work around for now, you can set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the location of the JSON credentials file.  For example, you could try the following with the test case you provided above:

```
GOOGLE_APPLICATION_CREDENTIALS=/tmp/.config/gcloud/application_default_credentials.json
```

**Comment by garrettjonesgoogle** [comment]
This work was done in https://github.com/google/google-auth-library-java/pull/63 . Closing this out.
